### ISSUE TITLE
New CentOS 7 environment has undefined gdal symbol

### ISSUE THREAD

**Issue by djhoese** [conda-forge/rasterio-feedstock#100]
Building a new environment fails with the following error:

```
$ python -c "from rasterio import Affine"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/users/davidh/anaconda3/envs/sift_new_env/lib/python3.6/site-packages/rasterio/__init__.py", line 22, in <module>
    from rasterio._base import gdal_version
ImportError: /data/users/davidh/anaconda3/envs/sift_new_env/lib/python3.6/site-packages/rasterio/../../../libgdal.so.20: undefined symbol: _ZN6libdap3DDSC1EPNS_15BaseTypeFactoryERKSs
```

This is similar but now exactly the same as #98. I'm creating the environment to install my own package called "sift" with:

```bash
conda create -n sift_new_env -c http://larch.ssec.wisc.edu/channels/sift python=3.6 sift
```

You'll notice that this only installs my own custom packages and a custom matplotlib build (to use PyQt4). See details below.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list 
# packages in environment at /data/users/davidh/anaconda3/envs/sift_new_env:
#
# Name                    Version                   Build  Channel
affine                    2.2.2                      py_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
attrs                     18.2.0                     py_0    conda-forge
blas                      1.0                         mkl  
bokeh                     1.0.4                 py36_1000    conda-forge
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
boto3                     1.9.82                     py_0    conda-forge
botocore                  1.12.82                    py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12              he56eebe_3    conda-forge
certifi                   2018.11.29            py36_1000    conda-forge
cffi                      1.11.5          py36h9745a5d_1001    conda-forge
cftime                    1.0.3.4         py36h3010b51_1000    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               0.6.1                      py_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
cryptography              2.3.1           py36hb7f436b_1000    conda-forge
curl                      7.63.0            h646f8bb_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cytoolz                   0.9.0.1         py36h14c3975_1001    conda-forge
dask                      1.0.0                      py_1    conda-forge
dask-core                 1.0.0                      py_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
distributed               1.25.2                py36_1000    conda-forge
docutils                  0.14                  py36_1001    conda-forge
eccodes                   2.9.0                h5fa7c4b_0    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
ffmpeg                    4.0.1                h0987f0c_0    conda-forge
fontconfig                2.13.0               hd36ec8e_5    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      2.3.2            py36hb00a9d7_0    conda-forge
geos                      3.6.2                hfc679d8_4    conda-forge
geotiff                   1.4.2             hfe6da40_1005    conda-forge
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
giflib                    5.1.4             h14c3975_1001    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
gnutls                    3.6.5             hd3a4fd2_1001    conda-forge
goesr                     0.5.2                      py_0    http://larch.ssec.wisc.edu/channels/sift
graphite2                 1.3.13            hf484d3e_1000    conda-forge
h5py                      2.8.0           py36hfb8609e_1004    conda-forge
harfbuzz                  1.8.5                h2bb21d5_0    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.3            hba1933b_1001    conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py36_1000    conda-forge
imageio                   2.4.1                 py36_1000    conda-forge
intel-openmp              2019.1                      144  
jasper                    1.900.1           h07fcdf6_1005    conda-forge
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.12.1               h470a237_1    conda-forge
kealib                    1.4.10            hc069b17_1000    conda-forge
kiwisolver                1.0.1           py36h6bb024c_1002    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libcurl                   7.63.0            h01ee5af_1000    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgdal                   2.3.2                hc73897a_0    conda-forge
libgfortran               3.0.0                         1    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
libnetcdf                 4.6.1             hc6a9f4b_1010    conda-forge
libpng                    1.6.34               ha92aebf_2    conda-forge
libpq                     10.6              h13b8bad_1000    conda-forge
libspatialite             4.3.0a            h9968ff2_1023    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
llvmlite                  0.26.0          py36hdbcaa40_1000    conda-forge
locket                    0.2.0                      py_2    conda-forge
markupsafe                1.1.0           py36h14c3975_1000    conda-forge
matplotlib                2.2.2                    py36_1    http://larch.ssec.wisc.edu/channels/sift
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py36h470a237_1    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
msgpack-python            0.6.0           py36h6bb024c_1000    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf4                   1.4.2           py36h2b0cf2a_1000    conda-forge
nettle                    3.4.1             h14c3975_1002    conda-forge
networkx                  2.2                        py_1    conda-forge
numba                     0.41.0          py36h637b7d7_1000    conda-forge
numpy                     1.15.4           py36h7e9f1db_0  
numpy-base                1.15.4           py36hde5b4d6_0  
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.0             hf38bd82_1003    conda-forge
openssl                   1.0.2p            h14c3975_1002    conda-forge
packaging                 18.0                       py_0    conda-forge
pandas                    0.23.4          py36h637b7d7_1000    conda-forge
pango                     1.40.14              h9105a7a_2    conda-forge
partd                     0.3.9                      py_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pillow                    5.2.0            py36h2dc6135_1    conda-forge
pip                       18.1                  py36_1000    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
poppler                   0.67.0               hb55ee21_1    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                10.6              h66cca7a_1000    conda-forge
proj4                     4.9.3                h470a237_8    conda-forge
psutil                    5.4.8           py36h14c3975_1000    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycparser                 2.19                       py_0    conda-forge
pygrib                    2.0.3            py36h5688137_0    conda-forge
pykdtree                  1.3.1           py36h3010b51_1002    conda-forge
pyopengl                  3.1.3b2                    py_0    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyproj                    1.9.5.1         py36h2944ce7_1006    conda-forge
pyqt                      4.11.4                   py36_3    conda-forge
pyqtgraph                 0.10.0                     py_5    conda-forge
pyresample                1.10.3          py36h637b7d7_1000    conda-forge
pyshp                     2.0.1                      py_0    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
pyspectral                0.8.4                      py_0    conda-forge
python                    3.6.7             hd21baee_1001    conda-forge
python-dateutil           2.7.5                      py_0    conda-forge
python-geotiepoints       1.1.7            py36h3010b51_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pywavelets                1.0.1           py36h3010b51_1000    conda-forge
pyyaml                    3.13            py36h14c3975_1001    conda-forge
qt                        4.8.7                         4  
quamash                   0.6.0                      py_0    http://larch.ssec.wisc.edu/channels/sift
rasterio                  1.0.13           py36h54a03ab_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.21.0                py36_1000    conda-forge
s3transfer                0.1.13                py36_1001    conda-forge
satpy                     0.10.0a0                   py_0    http://larch.ssec.wisc.edu/channels/sift
scikit-image              0.14.1          py36hf484d3e_1004    conda-forge
scipy                     1.1.0            py36h7c811a0_2  
setuptools                40.6.3                   py36_0    conda-forge
shapely                   1.6.4           py36h0c48222_1000    conda-forge
sift                      1.0.4                    py36_0    http://larch.ssec.wisc.edu/channels/sift
sip                       4.18                     py36_1    conda-forge
six                       1.12.0                py36_1000    conda-forge
snuggs                    1.4.1                      py_1    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlalchemy                1.2.16          py36h14c3975_1000    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
tblib                     1.3.2                      py_1    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   5.1.1           py36h14c3975_1000    conda-forge
tqdm                      4.29.1                     py_0    conda-forge
trollimage                1.6.3                      py_0    conda-forge
trollsift                 0.3.2                      py_0    conda-forge
tzcode                    2018g             h14c3975_1001    conda-forge
urllib3                   1.24.1                py36_1000    conda-forge
vispy                     0.6.0.dev0               py36_4    http://larch.ssec.wisc.edu/channels/sift
wheel                     0.32.3                   py36_0    conda-forge
x264                      1!152.20180717    h14c3975_1001    conda-forge
xarray                    0.11.2                py36_1000    conda-forge
xerces-c                  3.2.0                h5d6a6da_2    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h14c3975_1004    conda-forge
xorg-libsm                1.2.3             h4937e3b_1000    conda-forge
xorg-libx11               1.6.6             h14c3975_1000    conda-forge
xorg-libxau               1.0.8             h14c3975_1006    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xorg-libxext              1.3.3             h14c3975_1004    conda-forge
xorg-libxrender           0.9.10            h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : sift_new_env
    active env location : /data/users/davidh/anaconda3/envs/sift_new_env
            shell level : 1
       user config file : /home/davidh/.condarc
 populated config files : /home/davidh/.condarc
          conda version : 4.5.11
    conda-build version : 3.12.0
         python version : 3.6.1.final.0
       base environment : /data/users/davidh/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /data/users/davidh/anaconda3/pkgs
                          /home/davidh/.conda/pkgs
       envs directories : /data/users/davidh/anaconda3/envs
                          /home/davidh/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.14.2 CPython/3.6.1 Linux/3.10.0-327.3.1.el7.x86_64 centos/7 glibc/2.17
                UID:GID : 53807:700
             netrc file : None
           offline mode : False
```
</details>

**Comment by djhoese** [comment]
Looks like I can't get gdal 2.3.3 installed because my custom matplotlib has some dependency incompatibility. I still am not aware of an easy way to figure out the incompatibility between two packages. `conda info` isn't easy.

**Comment by djhoese** [comment]
This has been fixed by updating to a new version of gdal which was made possible after rebuilding my custom matplotlib to use a newer version of libpng.
