### ISSUE TITLE
Using copy.deepcopy on rasterio.crs.CRS(), causes TypeError: no default __reduce__ due to non-trivial __cinit__.

### ISSUE THREAD

**Issue by Marchen** [conda-forge/rasterio-feedstock#108]
On Windows and Linux, rasterio installed from conda-forge shows TypeError when using copy.deepcopy on rasterio.crs.CRS object.

Repro:
```python
import rasterio
import copy
crs = rasterio.crs.CRS()
copy.deepcopy(crs)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mic\Miniconda3\envs\rasterio_test\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\mic\Miniconda3\envs\rasterio_test\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\mic\Miniconda3\envs\rasterio_test\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\mic\Miniconda3\envs\rasterio_test\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\mic\Miniconda3\envs\rasterio_test\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)
  File "stringsource", line 2, in rasterio._crs._CRS.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

Because I couldn't reproduce the error with binary wheels created by Christoph Gohlke, I think this is something related with rasterio package on conda-forge.
https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal
https://www.lfd.uci.edu/~gohlke/pythonlibs/#rasterio

Full steps I used to reproduce the error in new environment:

```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.9.6
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>conda create -n rasterio_test python=3.7
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.6.2

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Users\mic\Miniconda3\envs\rasterio_test

  added / updated specs:
    - python=3.7


The following NEW packages will be INSTALLED:

    certifi:        2018.11.29-py37_1000 conda-forge
    pip:            19.0.1-py37_0        conda-forge
    python:         3.7.1-hc182675_1000  conda-forge
    setuptools:     40.7.3-py37_0        conda-forge
    vc:             14-0                 conda-forge
    vs2015_runtime: 14.0.25420-0         conda-forge
    wheel:          0.32.3-py37_0        conda-forge
    wincertstore:   0.2-py37_1002        conda-forge

Proceed ([y]/n)?

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use:
# > activate rasterio_test
#
# To deactivate an active environment, use:
# > deactivate
#
# * for power-users using bash, you must source
#


C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>conda install rasterio -n rasterio_test
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.12
  latest version: 4.6.2

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Users\mic\Miniconda3\envs\rasterio_test

  added / updated specs:
    - rasterio


The following NEW packages will be INSTALLED:

    affine:                  2.2.2-py_0                 conda-forge
    asn1crypto:              0.24.0-py37_1003           conda-forge
    attrs:                   18.2.0-py_0                conda-forge
    blas:                    1.0-mkl
    boost-cpp:               1.68.0-h6a4c333_1000       conda-forge
    boto3:                   1.9.87-py_0                conda-forge
    botocore:                1.12.88-py_0               conda-forge
    bzip2:                   1.0.6-hfa6e2cd_1002        conda-forge
    ca-certificates:         2018.11.29-ha4d7672_0      conda-forge
    cffi:                    1.11.5-py37hfa6e2cd_1001   conda-forge
    click:                   7.0-py_0                   conda-forge
    click-plugins:           1.0.4-py_0                 conda-forge
    cligj:                   0.5.0-py_0                 conda-forge
    cryptography:            2.5-py37h74b6da3_0         conda-forge
    curl:                    7.63.0-h4496350_1000       conda-forge
    docutils:                0.14-py37_1001             conda-forge
    expat:                   2.2.5-he025d50_1002        conda-forge
    freetype:                2.9.1-h5db478b_1005        conda-forge
    freexl:                  1.0.5-hd288d7e_1002        conda-forge
    geos:                    3.7.1-he025d50_1000        conda-forge
    geotiff:                 1.4.3-h8408f58_1000        conda-forge
    gettext:                 0.19.8.1-hb01d8f6_1001     conda-forge
    glib:                    2.58.2-hc0c2ac7_1001       conda-forge
    hdf4:                    4.2.13-hf8e6fe8_1002       conda-forge
    hdf5:                    1.10.4-nompi_hcc15c50_1105 conda-forge
    icc_rt:                  2019.0.0-h0cc432a_1
    idna:                    2.8-py37_1000              conda-forge
    intel-openmp:            2019.1-144
    jmespath:                0.9.3-py_1                 conda-forge
    jpeg:                    9c-hfa6e2cd_1001           conda-forge
    kealib:                  1.4.10-heacb130_1002       conda-forge
    krb5:                    1.16.3-h038dc86_1000       conda-forge
    libcurl:                 7.63.0-h4496350_1000       conda-forge
    libffi:                  3.2.1-h6538335_1005        conda-forge
    libgdal:                 2.4.0-haf7df99_1002        conda-forge
    libiconv:                1.15-hfa6e2cd_1004         conda-forge
    libkml:                  1.3.0-h4fd0f3b_1009        conda-forge
    libnetcdf:               4.6.2-h396784b_1001        conda-forge
    libpng:                  1.6.36-h7602738_1000       conda-forge
    libpq:                   10.6-h4c6b53d_1000         conda-forge
    libspatialite:           4.3.0a-h6a0152f_1026       conda-forge
    libssh2:                 1.8.0-hc4dcbb0_1003        conda-forge
    libtiff:                 4.0.10-h36446d0_1001       conda-forge
    libxml2:                 2.9.8-h9ce36c8_1005        conda-forge
    m2w64-expat:             2.1.1-2
    m2w64-gcc-libgfortran:   5.3.0-6
    m2w64-gcc-libs:          5.3.0-7
    m2w64-gcc-libs-core:     5.3.0-7
    m2w64-gettext:           0.19.7-2
    m2w64-gmp:               6.1.0-2
    m2w64-libiconv:          1.14-6
    m2w64-libwinpthread-git: 5.0.0.4634.697f757-2
    m2w64-xz:                5.2.2-2
    mkl:                     2019.1-144
    msys2-conda-epoch:       20160418-1
    numpy:                   1.11.3-py37h0aa5519_11
    numpy-base:              1.11.3-py37h2a9b21d_11
    openjpeg:                2.3.0-h25a6d84_1003        conda-forge
    openssl:                 1.0.2p-hfa6e2cd_1002       conda-forge
    pcre:                    8.41-h6538335_1003         conda-forge
    poppler:                 0.67.0-heddaa77_6          conda-forge
    poppler-data:            0.4.9-1                    conda-forge
    postgresql:              10.6-hdce66b5_1000         conda-forge
    proj4:                   5.2.0-hfa6e2cd_1001        conda-forge
    pycparser:               2.19-py_0                  conda-forge
    pyopenssl:               19.0.0-py37_0              conda-forge
    pyparsing:               2.3.1-py_0                 conda-forge
    pysocks:                 1.6.8-py37_1002            conda-forge
    python-dateutil:         2.8.0-py_0                 conda-forge
    rasterio:                1.0.16-py37hbf02ebe_0      conda-forge
    s3transfer:              0.1.13-py37_1001           conda-forge
    six:                     1.12.0-py37_1000           conda-forge
    snuggs:                  1.4.1-py_1                 conda-forge
    sqlite:                  3.26.0-hfa6e2cd_1000       conda-forge
    tk:                      8.6.9-hfa6e2cd_1000        conda-forge
    urllib3:                 1.24.1-py37_1000           conda-forge
    win_inet_pton:           1.0.1-py37_1002            conda-forge
    xerces-c:                3.2.2-h6538335_1001        conda-forge
    xz:                      5.2.4-h2fa13f4_1001        conda-forge
    zlib:                    1.2.11-h2fa13f4_1004       conda-forge

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>activate rasterio_test

(rasterio_test) C:\Program Files (x86)\Microsoft Visual Studio\2017\Community>python
Python 3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 19:01:41) [MSC v.1900 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import rasterio
>>> import copy
>>> crs = rasterio.crs.CRS()
>>> copy.deepcopy(crs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mic\Miniconda3\envs\rasterio_test\lib\copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "C:\Users\mic\Miniconda3\envs\rasterio_test\lib\copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "C:\Users\mic\Miniconda3\envs\rasterio_test\lib\copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "C:\Users\mic\Miniconda3\envs\rasterio_test\lib\copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "C:\Users\mic\Miniconda3\envs\rasterio_test\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)
  File "stringsource", line 2, in rasterio._crs._CRS.__reduce_cython__
TypeError: no default __reduce__ due to non-trivial __cinit__
```

Thanks!

<br/>
Environment (<code>conda list</code>):
<details>

```
On Windows (Windows 10 Pro)

# packages in environment at C:\Users\mic\Miniconda3\envs\rasterio_test:
#
# Name                    Version                   Build  Channel
affine                    2.2.2                      py_0    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
attrs                     18.2.0                     py_0    conda-forge
blas                      1.0                         mkl
boost-cpp                 1.68.0            h6a4c333_1000    conda-forge
boto3                     1.9.87                     py_0    conda-forge
botocore                  1.12.88                    py_0    conda-forge
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
certifi                   2018.11.29            py37_1000    conda-forge
cffi                      1.11.5          py37hfa6e2cd_1001    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cryptography              2.5              py37h74b6da3_0    conda-forge
curl                      7.63.0            h4496350_1000    conda-forge
docutils                  0.14                  py37_1001    conda-forge
expat                     2.2.5             he025d50_1002    conda-forge
freetype                  2.9.1             h5db478b_1005    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
geos                      3.7.1             he025d50_1000    conda-forge
geotiff                   1.4.3             h8408f58_1000    conda-forge
gettext                   0.19.8.1          hb01d8f6_1001    conda-forge
glib                      2.58.2            hc0c2ac7_1001    conda-forge
hdf4                      4.2.13            hf8e6fe8_1002    conda-forge
hdf5                      1.10.4          nompi_hcc15c50_1105    conda-forge
icc_rt                    2019.0.0             h0cc432a_1
idna                      2.8                   py37_1000    conda-forge
intel-openmp              2019.1                      144
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
kealib                    1.4.10            heacb130_1002    conda-forge
krb5                      1.16.3            h038dc86_1000    conda-forge
libcurl                   7.63.0            h4496350_1000    conda-forge
libffi                    3.2.1             h6538335_1005    conda-forge
libgdal                   2.4.0             haf7df99_1002    conda-forge
libiconv                  1.15              hfa6e2cd_1004    conda-forge
libkml                    1.3.0             h4fd0f3b_1009    conda-forge
libnetcdf                 4.6.2             h396784b_1001    conda-forge
libpng                    1.6.36            h7602738_1000    conda-forge
libpq                     10.6              h4c6b53d_1000    conda-forge
libspatialite             4.3.0a            h6a0152f_1026    conda-forge
libssh2                   1.8.0             hc4dcbb0_1003    conda-forge
libtiff                   4.0.10            h36446d0_1001    conda-forge
libxml2                   2.9.8             h9ce36c8_1005    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
mkl                       2019.1                      144
msys2-conda-epoch         20160418                      1
numpy                     1.11.3          py37h0aa5519_11
numpy-base                1.11.3          py37h2a9b21d_11
openjpeg                  2.3.0             h25a6d84_1003    conda-forge
openssl                   1.0.2p            hfa6e2cd_1002    conda-forge
pcre                      8.41              h6538335_1003    conda-forge
pip                       19.0.1                   py37_0    conda-forge
poppler                   0.67.0               heddaa77_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                10.6              hdce66b5_1000    conda-forge
proj4                     5.2.0             hfa6e2cd_1001    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
python                    3.7.1             hc182675_1000    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
rasterio                  1.0.16           py37hbf02ebe_0    conda-forge
s3transfer                0.1.13                py37_1001    conda-forge
setuptools                40.7.3                   py37_0    conda-forge
six                       1.12.0                py37_1000    conda-forge
snuggs                    1.4.1                      py_1    conda-forge
sqlite                    3.26.0            hfa6e2cd_1000    conda-forge
tk                        8.6.9             hfa6e2cd_1000    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wheel                     0.32.3                   py37_0    conda-forge
win_inet_pton             1.0.1                 py37_1002    conda-forge
wincertstore              0.2                   py37_1002    conda-forge
xerces-c                  3.2.2             h6538335_1001    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
zlib                      1.2.11            h2fa13f4_1004    conda-forge


On Linux (Kubuntu 18.04)

# packages in environment at /home/mic/miniconda3/envs/s15senarion:
#
# Name                    Version                   Build  Channel
affine                    2.2.2                      py_0    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
atk                       2.25.90           hb9dd440_1002    conda-forge
attrs                     18.2.0                     py_0    conda-forge
blas                      1.0                         mkl  
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
boto3                     1.9.87                     py_0    conda-forge
botocore                  1.12.87                    py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.16.0            ha4e643d_1000    conda-forge
certifi                   2018.11.29            py37_1000    conda-forge
cffi                      1.11.5          py37h9745a5d_1001    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cryptography              2.5              py37hb7f436b_0    conda-forge
curl                      7.63.0            h646f8bb_1000    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0            h4e0c4b3_1000    conda-forge
descartes                 1.1.0                      py_2    conda-forge
docutils                  0.14                  py37_1001    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
fiona                     1.8.4           py37h1c6dbfb_1002    conda-forge
fontconfig                2.13.1            h2176d3f_1000    conda-forge
freetype                  2.9.1             h94bbf69_1005    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      2.4.0           py37h1c6dbfb_1002    conda-forge
gdk-pixbuf                2.36.12           h49783d7_1002    conda-forge
geopandas                 0.4.0                      py_1    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
geotiff                   1.4.3             h1105359_1000    conda-forge
gettext                   0.19.8.1          h9745a5d_1001    conda-forge
giflib                    5.1.4             h14c3975_1001    conda-forge
glib                      2.58.2            hf63aee3_1001    conda-forge
gobject-introspection     1.58.2          py37h2da5eee_1000    conda-forge
graphite2                 1.3.13            hf484d3e_1000    conda-forge
gstreamer                 1.14.4            h66beb1c_1001    conda-forge
gtk2                      2.24.31           hb68c50a_1001    conda-forge
harfbuzz                  2.3.1                h6824563_0    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h11e915b_1105    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
intel-openmp              2019.1                      144  
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
kealib                    1.4.10            he7154bc_1002    conda-forge
kiwisolver                1.0.1           py37h6bb024c_1002    conda-forge
krb5                      1.16.3            hc83ff2d_1000    conda-forge
libcurl                   7.63.0            h01ee5af_1000    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             hf484d3e_1005    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgdal                   2.4.0             h982c1cc_1002    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h14c3975_1004    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.36            h84994c4_1000    conda-forge
libpq                     10.6              h13b8bad_1000    conda-forge
libspatialindex           1.8.5             hf484d3e_1003    conda-forge
libspatialite             4.3.0a            hb5ec416_1026    conda-forge
libssh2                   1.8.0             h1ad7b7a_1003    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h648cc4a_1001    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.8             h143f9aa_1005    conda-forge
matplotlib                3.0.2                 py37_1002    conda-forge
matplotlib-base           3.0.2           py37h167e16e_1002    conda-forge
mkl                       2019.1                      144  
mkl_fft                   1.0.10           py37h14c3975_1    conda-forge
mkl_random                1.0.2            py37h637b7d7_2    conda-forge
munch                     2.3.2                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.15.4           py37h7e9f1db_0  
numpy-base                1.15.4           py37hde5b4d6_0  
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.0             hf38bd82_1003    conda-forge
openssl                   1.0.2p            h14c3975_1002    conda-forge
palettable                3.1.1                      py_0    conda-forge
pandas                    0.24.1           py37hf484d3e_0    conda-forge
pango                     1.40.14           h4ea9474_1004    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pillow                    5.4.1           py37h00a061d_1000    conda-forge
pip                       19.0.1                   py37_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
poppler                   0.67.0               h2ad7f00_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                10.6              h66cca7a_1000    conda-forge
proj4                     5.2.0             h14c3975_1001    conda-forge
psycopg2                  2.7.7            py37hb7f436b_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
pycparser                 2.19                       py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.3.1                      py_0    conda-forge
pyproj                    1.9.6           py37hc0953d3_1000    conda-forge
pyqt                      5.6.0           py37h13b7fb3_1008    conda-forge
pysal                     2.0.0                      py_0    conda-forge
pysocks                   1.6.8                 py37_1002    conda-forge
python                    3.7.1             hd21baee_1000    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
qt                        5.6.2             hce4f676_1013    conda-forge
rasterio                  1.0.16           py37h286bbcc_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
rtree                     0.8.3                 py37_1000    conda-forge
s3transfer                0.1.13                py37_1001    conda-forge
scipy                     1.2.0            py37h7c811a0_0  
seaborn                   0.9.0                      py_0    conda-forge
setuptools                40.7.3                   py37_0    conda-forge
shapely                   1.6.4           py37h092830f_1002    conda-forge
sip                       4.18.1          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
snuggs                    1.4.1                      py_1    conda-forge
sqlalchemy                1.2.17           py37h14c3975_0    conda-forge
sqlite                    3.26.0            h67949de_1000    conda-forge
statsmodels               0.9.0           py37h3010b51_1000    conda-forge
tk                        8.6.9             h84994c4_1000    conda-forge
tornado                   5.1.1           py37h14c3975_1000    conda-forge
tzcode                    2018g             h14c3975_1001    conda-forge
urllib3                   1.24.1                py37_1000    conda-forge
wheel                     0.32.3                   py37_0    conda-forge
xerces-c                  3.2.2             hac72e42_1001    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.9             h14c3975_1004    conda-forge
xorg-libsm                1.2.3             h4937e3b_1000    conda-forge
xorg-libx11               1.6.7             h14c3975_1000    conda-forge
xorg-libxau               1.0.8             h14c3975_1006    conda-forge
xorg-libxdmcp             1.1.2             h14c3975_1007    conda-forge
xorg-libxext              1.3.3             h14c3975_1004    conda-forge
xorg-libxrender           0.9.10            h14c3975_1002    conda-forge
xorg-libxt                1.1.5             h14c3975_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
On Windows (Windows 10 Pro)

     active environment : rasterio_test
    active env location : C:\Users\mic\Miniconda3\envs\rasterio_test
            shell level : 1
       user config file : C:\Users\mic\.condarc
 populated config files : C:\Users\mic\.condarc
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.7.0.final.0
       base environment : C:\Users\mic\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\mic\Miniconda3\pkgs
                          C:\Users\mic\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\mic\Miniconda3\envs
                          C:\Users\mic\AppData\Local\conda\conda\envs
                          C:\Users\mic\.conda\envs
               platform : win-64
             user-agent : conda/4.5.12 requests/2.19.1 CPython/3.7.0 Windows/10 Windows/10.0.18323
          administrator : False
             netrc file : None
           offline mode : False


On Linux (Kubuntu 18.04)

     active environment : s15senarion
    active env location : /home/mic/miniconda3/envs/s15senarion
            shell level : 1
       user config file : /home/mic/.condarc
 populated config files : /home/mic/.condarc
          conda version : 4.5.12
    conda-build version : not installed
         python version : 3.6.8.final.0
       base environment : /home/mic/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/mic/miniconda3/pkgs
                          /home/mic/.conda/pkgs
       envs directories : /home/mic/miniconda3/envs
                          /home/mic/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.18.4 CPython/3.6.8 Linux/4.15.0-44-generic ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by ocefpaf** [comment]
I don't think this is a packaging issue. It looks like [Gohlke's version is 1.10.14](https://www.lfd.uci.edu/~gohlke/pythonlibs/#rasterio) and you are installing `rasterio 1.0.16` from `conda-forge`. Can you try to use the same version and, if things work, report it upstream.

**Comment by Marchen** [comment]
Thank your for your reply and checking. I will try with the latest version of rasterio and if it produces same error, I will report the issue to [rasterio](https://github.com/mapbox/rasterio).

**Comment by sgillies** [comment]
@Marchen sorry about the trouble. I never intended the rasterio CRS object to be so much like a dict and we've changed the implementation. It now provides the collections.Mapping interface but nothing more.

**Comment by Marchen** [comment]
@sgillies thanks for the reply. I'm using a class conducting raster operations which uses the rasterio for an IO driver and keeps a CRS object within it. When I used deepcopy to replicate an object of the class, I encountered the error. I'm happy if you can make the CRS object _deepcopy-able_, but because I could create a work around for my use case, it would not be a huge problem, at least for me.

Anyway, thanks for your great work. It helps my projects every time.
