### ISSUE TITLE
Cannot install rasterio due to libpoppler issue

### ISSUE THREAD

**Issue by himat** [conda-forge/rasterio-feedstock#133]
Issue: Cannot install rasterio in a new env with nothing else installed

I first tried installing rasterio with conda but got this error:
```
>>> import rasterio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import (
ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory
```

After looking at previous issues on this, such as https://github.com/conda-forge/rasterio-feedstock/issues/58, I tried setting strict channel priority. But this showed that they were totally incompatible
```
(base)
ubuntu@ip-172-31-18-242:~/repo
$ conda config --set channel_priority strict

(base)
ubuntu@ip-172-31-18-242:~/repo                                                                                          
$ conda create --name manual python=3.6.5 rasterio -c conda-forge
Collecting package metadata (current_repodata.json): done
Solving environment: failed
Collecting package metadata (repodata.json): done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

  - rasterio -> affine[version='>=1.3.0'] -> python -> bzip2[version='>=1.0.6,<2.0a0'] -> libgcc-ng[version='>=7.3.0']
  - rasterio -> affine[version='>=1.3.0'] -> python -> libffi[version='>=3.2.1,<3.3.0a0'] -> libstdcxx-ng[version='>=7.3.0']
  - rasterio -> affine[version='>=1.3.0'] -> python -> ncurses[version='>=6.1,<6.2.0a0']
  - rasterio -> affine[version='>=1.3.0'] -> python -> openssl[version='>=1.1.1a,<1.1.2a'] -> ca-certificates
  - rasterio -> affine[version='>=1.3.0'] -> python -> pip -> setuptools -> certifi[version='>=2016.09']
  - rasterio -> affine[version='>=1.3.0'] -> python -> pip -> wheel
  - rasterio -> affine[version='>=1.3.0'] -> python -> readline[version='>=8.0,<9.0a0']
  - rasterio -> affine[version='>=1.3.0'] -> python -> sqlite[version='>=3.28.0,<4.0a0'] -> libedit[version='>=3.1.20181209,<3.2.0a0']
  - rasterio -> affine[version='>=1.3.0'] -> python -> tk[version='>=8.6.9,<8.7.0a0'] -> zlib[version='>=1.2.11,<1.3.0a0']
  - rasterio -> affine[version='>=1.3.0'] -> python -> xz[version='>=5.2.4,<5.3.0a0']
  - rasterio -> attrs[version='>=16.0.0'] -> hypothesis -> coverage
  - rasterio -> attrs[version='>=16.0.0'] -> hypothesis -> enum34
  - rasterio -> attrs[version='>=16.0.0'] -> pympler
  - rasterio -> attrs[version='>=16.0.0'] -> zope
  - rasterio -> attrs[version='>=16.0.0'] -> zope.interface
  - rasterio -> boto3[version='>=1.2.4']
  - rasterio -> click-plugins
  - rasterio -> click[version='>=4,<8']
  - rasterio -> cligj[version='>=0.5']
  - rasterio -> gdal=2.2
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> cfitsio[version='>=3.470,<3.471.0a0'] -> libcurl[version='>=7.64.1,<8.0a0'] -> krb5[version='>=1.16.3,<1.17.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> cfitsio[version='>=3.470,<3.471.0a0'] -> libcurl[version='>=7.64.1,<8.0a0'] -> libssh2[version='>=1.8.2,<1.9.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> cfitsio[version='>=3.470,<3.471.0a0'] -> libgfortran-ng[version='>=7,<8.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> expat[version='>=2.2.5,<2.3.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> freexl[version='>=1.0.5,<2.0a0'] -> libiconv==1.15
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> geos[version='>=3.7.2,<3.7.3.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> geotiff[version='>=1.5.1,<1.5.2.0a0'] -> jpeg[version='>=9c,<10a']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> geotiff[version='>=1.5.1,<1.5.2.0a0'] -> libtiff[version='>=4.0.9,<5.0a0'] -> zstd[version='>=1.4.0,<1.4.1.0a0'] -> lz4-c[version='>=1.8.3,<1.8.4.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> geotiff[version='>=1.5.1,<1.5.2.0a0'] -> proj4[version='>=6.1.0,<6.1.1.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> giflib[version='>=5.1.7,<5.1.8.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> hdf4[version='>=4.2.13,<4.3.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> hdf5[version='>=1.10.5,<1.10.6.0a0'] -> mpich[version='>=3.2,<3.3.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> hdf5[version='>=1.10.5,<1.10.6.0a0'] -> openmpi[version='>=3.1,<3.2.0a0'] -> libgfortran[version='>=3.0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> hdf5[version='>=1.10.5,<1.10.6.0a0'] -> openmpi[version='>=3.1,<3.2.0a0'] -> mpi==1.0=openmpi
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> json-c[version='>=0.13.1,<0.14.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> kealib[version='>=1.4.10,<1.5.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> libdap4[version='>=3.19.1,<3.20.0a0'] -> curl[version='>=7.59.0,<8.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> libdap4[version='>=3.19.1,<3.20.0a0'] -> libuuid[version='>=2.32.1,<3.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> libdap4[version='>=3.19.1,<3.20.0a0'] -> libxml2[version='>=2.9.8,<2.10.0a0'] -> icu[version='>=58.2,<59.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> libdap4[version='>=3.19.1,<3.20.0a0'] -> util-linux
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> libkml[version='>=1.3.0,<1.4.0a0'] -> boost-cpp[version='>=1.70.0,<1.70.1.0a0'] -> libboost[version='<0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> libnetcdf[version='>=4.6.2,<4.6.3.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> libpng[version='>=1.6.35,<1.7.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> libpq[version='>=11.4,<12.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> libspatialite[version='>=4.3.0a,<4.4.0a0'] -> libgcc -> cloog==0.18.0 -> gmp==5.1.2
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> libspatialite[version='>=4.3.0a,<4.4.0a0'] -> libgcc -> cloog==0.18.0 -> isl==0.12.2
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> libspatialite[version='>=4.3.0a,<4.4.0a0'] -> libgcc -> mpc[version='>=0.8.0'] -> mpfr[version='>=4.0.1,<5.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> openjpeg[version='>=2.3.1,<2.4.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> pcre[version='>=8.41,<9.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> poppler[version='>=0.67.0,<0.68.0a0'] -> cairo[version='>=1.14.12,<1.15.0a0'] -> fontconfig[version='>=2.13.1,<3.0a0'] -> freetype[version='>=2.9.1,<3.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> poppler[version='>=0.67.0,<0.68.0a0'] -> cairo[version='>=1.14.12,<1.15.0a0'] -> glib[version='>=2.58.2,<2.59.0a0'] -> gettext[version='>=0.19.8.1,<1.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> poppler[version='>=0.67.0,<0.68.0a0'] -> cairo[version='>=1.14.12,<1.15.0a0'] -> libxcb -> pthread-stubs
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> poppler[version='>=0.67.0,<0.68.0a0'] -> cairo[version='>=1.14.12,<1.15.0a0'] -> libxcb -> xorg-libxau
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> poppler[version='>=0.67.0,<0.68.0a0'] -> cairo[version='>=1.14.12,<1.15.0a0'] -> libxcb -> xorg-libxdmcp
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> poppler[version='>=0.67.0,<0.68.0a0'] -> cairo[version='>=1.14.12,<1.15.0a0'] -> pixman[version='>=0.34.0,<0.35.0a0']
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> poppler[version='>=0.67.0,<0.68.0a0'] -> cairo[version='>=1.14.12,<1.15.0a0'] -> xorg-libice
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> poppler[version='>=0.67.0,<0.68.0a0'] -> cairo[version='>=1.14.12,<1.15.0a0'] -> xorg-libsm
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> poppler[version='>=0.67.0,<0.68.0a0'] -> cairo[version='>=1.14.12,<1.15.0a0'] -> xorg-libx11 -> xorg-kbproto
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> poppler[version='>=0.67.0,<0.68.0a0'] -> cairo[version='>=1.14.12,<1.15.0a0'] -> xorg-libx11 -> xorg-libxcb=1 -> xorg-libpthread-stubs
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> poppler[version='>=0.67.0,<0.68.0a0'] -> cairo[version='>=1.14.12,<1.15.0a0'] -> xorg-libx11 -> xorg-xproto
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> poppler[version='>=0.67.0,<0.68.0a0'] -> cairo[version='>=1.14.12,<1.15.0a0'] -> xorg-libxext -> xorg-xextproto
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> poppler[version='>=0.67.0,<0.68.0a0'] -> cairo[version='>=1.14.12,<1.15.0a0'] -> xorg-libxrender -> xorg-renderproto
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> poppler[version='>=0.67.0,<0.68.0a0'] -> poppler-data
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> postgresql -> libxslt=1.1
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> postgresql -> tzcode
  - rasterio -> libgdal[version='>=2.4.1,<2.5.0a0'] -> xerces-c[version='>=3.2.2,<3.2.3.0a0']
  - rasterio -> numpy[version='>=1.14.6,<2.0a0'] -> mkl_fft[version='>=1.0.6,<2.0a0'] -> numpy-base[version='>=1.0.6,<2.0a0']
  - rasterio -> numpy[version='>=1.14.6,<2.0a0'] -> mkl_random[version='>=1.0.2,<2.0a0']
  - rasterio -> snuggs[version='>=1.4.1']


Note that strict channel priority may have removed packages required for satisfiability.
```

<br/>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
/home/ubuntu/anaconda3/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.3) or chardet (3.0.4) doesn't match a s
upported version!
  RequestsDependencyWarning)

     active environment : base
    active env location : /home/ubuntu/anaconda3
            shell level : 1
       user config file : /home/ubuntu/.condarc
 populated config files : /home/ubuntu/.condarc
          conda version : 4.5.12
    conda-build version : 3.10.5
         python version : 3.6.5.final.0
       base environment : /home/ubuntu/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /home/ubuntu/anaconda3/pkgs
       envs directories : /home/ubuntu/anaconda3/envs
                          /home/ubuntu/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.12 requests/2.20.0 CPython/3.6.5 Linux/4.4.0-1087-aws ubuntu/16.04 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by ocefpaf** [comment]
It should be fixed now. Can you try again? (Please re-open if the problem persists.)

**Comment by ocefpaf** [comment]
BTW, you probably won't be able to use a tight pin on Python like that. You'll have to use `python=3.6` instead.
