### ISSUE TITLE
ImportError: dlopen(....../python3.6/site-packages/rasterio/_base.cpython-36m-darwin.so, 2): Symbol not found: _crc32

### ISSUE THREAD

**Issue by lwasser** [conda-forge/rasterio-feedstock#161]
Issue:

👋 hi there @ocefpaf !! me, yet again. i'm running into some issues with rasterio (i think) on MAC.
Essentially it's throwing errors for our earthpy build: example

https://travis-ci.org/github/earthlab/earthpy/jobs/680217713#L1887

At first it was working just fine for me locally on my mac. But then i rebuilt the environment and got the following failure when running `pytest`. 

Here is what i've tried so far (each time rebuilding the environment completely):

1. i've added all packages installed via `pip install -r dev-requirements.txt` to my conda envt just in case it was a pip / conda forge issue - so i just installed stuff using the envt and conda forge - no pip.
2. i've updated to python version 3.7 and reinstalled the envt

I'm really open to trying something different. this is oddly mac specific so i'm not sure what else to try but i can test it locally. the travis build instructions are here.

https://github.com/earthlab/earthpy/blob/master/.travis/install.sh

```
(earthpy-dev) CIRES-EL-LM-020:earthpy leahwasser$ pytest
========================================================== test session starts ==========================================================
platform darwin -- Python 3.7.6, pytest-5.4.1, py-1.8.1, pluggy-0.13.0
rootdir: /Users/leahwasser/Documents/github/0-python/earthpy, inifile: setup.cfg, testpaths: earthpy/tests
plugins: cov-2.8.1
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/_pytest/main.py", line 191, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/_pytest/main.py", line 246, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/manager.py", line 92, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/manager.py", line 86, in <lambda>
INTERNALERROR>     firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
INTERNALERROR>   File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/callers.py", line 182, in _multicall
INTERNALERROR>     next(gen)  # first yield
INTERNALERROR>   File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/_pytest/warnings.py", line 125, in pytest_collection
INTERNALERROR>     config=config, ihook=config.hook, when="collect", item=None
INTERNALERROR>   File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/contextlib.py", line 112, in __enter__
INTERNALERROR>     return next(self.gen)
INTERNALERROR>   File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/_pytest/warnings.py", line 82, in catch_warnings_for_item
INTERNALERROR>     _setoption(warnings, arg)
INTERNALERROR>   File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/_pytest/warnings.py", line 21, in _setoption
INTERNALERROR>     category = wmod._getcategory(category)
INTERNALERROR>   File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/warnings.py", line 266, in _getcategory
INTERNALERROR>     raise _OptionError("invalid module name: %r" % (module,)) from None
INTERNALERROR> warnings._OptionError: invalid module name: 'rasterio.errors'
Traceback (most recent call last):
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/bin/pytest", line 11, in <module>
    sys.exit(main())
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/_pytest/config/__init__.py", line 125, in main
    config=config
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/_pytest/main.py", line 240, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/_pytest/main.py", line 229, in wrap_session
    session=session, exitstatus=session.exitstatus
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/manager.py", line 92, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/manager.py", line 86, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/_pytest/terminal.py", line 716, in pytest_sessionfinish
    outcome.get_result()
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/pluggy/callers.py", line 182, in _multicall
    next(gen)  # first yield
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/_pytest/warnings.py", line 143, in pytest_sessionfinish
    config=config, ihook=config.hook, when="config", item=None
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/_pytest/warnings.py", line 82, in catch_warnings_for_item
    _setoption(warnings, arg)
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/site-packages/_pytest/warnings.py", line 21, in _setoption
    category = wmod._getcategory(category)
  File "/Users/leahwasser/miniconda3/envs/earthpy-dev/lib/python3.7/warnings.py", line 266, in _getcategory
    raise _OptionError("invalid module name: %r" % (module,)) from None
warnings._OptionError: invalid module name: 'rasterio.errors'
```

To recreate, following this:

https://github.com/earthlab/earthpy/blob/master/CONTRIBUTING.rst 

But note that this failure is occuring on multiple builds right now with spatial dependencies. 

## A WORKING BUILD: 

JUST FOR GIGGLES - here is my local environment BEFORE updating when all was running nicely. i took a "snapshot" of the envt specs just in case it would help.
```
CURRENT INSTALL:

(earthpy-dev) CIRES-EL-LM-020:earthpy leahwasser$ conda list
# packages in environment at /Users/leahwasser/miniconda3/envs/earthpy-dev:
#
# Name                    Version                   Build  Channel
affine                    2.3.0                      py_0    conda-forge
alabaster                 0.7.12                   pypi_0    pypi
argh                      0.26.2                   pypi_0    pypi
aspy-yaml                 1.3.0                    pypi_0    pypi
atomicwrites              1.3.0                    pypi_0    pypi
attrs                     19.3.0                     py_0    conda-forge
babel                     2.7.0                    pypi_0    pypi
boost-cpp                 1.70.0               h75728bb_2    conda-forge
bumpversion               0.5.3                    pypi_0    pypi
bzip2                     1.0.8                h0b31af3_2    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cairo                     1.16.0            he1c11cd_1002    conda-forge
certifi                   2020.4.5.1       py36h9f0ad1d_0    conda-forge
cfgv                      2.0.1                    pypi_0    pypi
cfitsio                   3.470                h84d2f63_2    conda-forge
chardet                   3.0.4                    pypi_0    pypi
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.2.2                      py_1    conda-forge
codecov                   2.0.22                   pypi_0    pypi
coverage                  4.5.4                    pypi_0    pypi
curl                      7.65.3               h22ea746_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py36h0b31af3_0    conda-forge
dask-core                 2.9.1                      py_0    conda-forge
decorator                 4.4.1                      py_0    conda-forge
docutils                  0.15.2                   pypi_0    pypi
earthpy                   0.8.0                     dev_0    <develop>
entrypoints               0.3             py36h9f0ad1d_1001    conda-forge
expat                     2.2.9                h4a8c4bd_2    conda-forge
filelock                  3.0.12                   pypi_0    pypi
fiona                     1.8.13           py36he71f6a4_0    conda-forge
flake8                    3.7.9            py36h9f0ad1d_1    conda-forge
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.10.0               h24853df_1    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
gdal                      3.0.3            py36h97c3584_0    conda-forge
geopandas                 0.7.0                      py_1    conda-forge
geos                      3.8.0                h4a8c4bd_0    conda-forge
geotiff                   1.5.1                hc9fff18_8    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.2.1                h0b31af3_1    conda-forge
glib                      2.58.3          py36h577aef8_1002    conda-forge
hdf4                      4.2.13            h84186c3_1003    conda-forge
hdf5                      1.10.5          nompi_h3e39495_1104    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
identify                  1.4.7                    pypi_0    pypi
idna                      2.8                      pypi_0    pypi
imageio                   2.6.1                    py36_0    conda-forge
imagesize                 1.1.0                    pypi_0    pypi
importlib-metadata        1.5.2                    pypi_0    pypi
importlib-resources       1.0.2                    pypi_0    pypi
jinja2                    2.10.3                   pypi_0    pypi
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
kealib                    1.4.10            h6659575_1005    conda-forge
kiwisolver                1.1.0            py36ha1b3eb9_0    conda-forge
krb5                      1.16.4               h1752a42_0    conda-forge
libblas                   3.8.0               14_openblas    conda-forge
libcblas                  3.8.0               14_openblas    conda-forge
libcurl                   7.65.3               h16faf7d_0    conda-forge
libcxx                    9.0.1                         1    conda-forge
libdap4                   3.20.4               habf5908_0    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h6de7cb9_1006    conda-forge
libgdal                   3.0.3                hf96e369_0    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h01d97ff_1005    conda-forge
libkml                    1.3.0             hed7d534_1010    conda-forge
liblapack                 3.8.0               14_openblas    conda-forge
libnetcdf                 4.7.3           nompi_hec86efb_100    conda-forge
libopenblas               0.3.7                h3d69b6c_7    conda-forge
libpng                    1.6.37               h2573ce8_0    conda-forge
libpq                     12.1                 h31a01ba_0    conda-forge
libspatialindex           1.9.3                h4a8c4bd_1    conda-forge
libspatialite             4.3.0a            h9c28a66_1034    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.1.0                ha78913b_3    conda-forge
libwebp                   1.0.2                hd3bf737_5    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
livereload                2.6.1                    pypi_0    pypi
llvm-openmp               9.0.1                h28b9765_1    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
m2r                       0.2.1                    pypi_0    pypi
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.1.2                    py36_1    conda-forge
matplotlib-base           3.1.2            py36h11da6c2_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4                    pypi_0    pypi
more-itertools            7.2.0                    pypi_0    pypi
multidict                 4.5.2                    pypi_0    pypi
munch                     2.5.0                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
networkx                  2.4                        py_0    conda-forge
nodeenv                   1.3.3                    pypi_0    pypi
numpy                     1.17.3           py36hde6bac1_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                hcdae239_3    conda-forge
openssl                   1.1.1g               h0b31af3_0    conda-forge
packaging                 19.2                     pypi_0    pypi
pandas                    0.25.3           py36h4f17bb1_0    conda-forge
pathtools                 0.1.2                    pypi_0    pypi
pcre                      8.43                 h4a8c4bd_0    conda-forge
pillow                    7.0.0            py36h918e99a_0    conda-forge
pip                       19.3.1                   py36_0    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
pluggy                    0.13.0                   pypi_0    pypi
poppler                   0.67.0               h16886b5_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
port-for                  0.3.1                    pypi_0    pypi
postgresql                12.1                 h26bc10f_0    conda-forge
pre-commit                1.21.0                   pypi_0    pypi
proj                      6.3.0                h773a61f_0    conda-forge
py                        1.8.0                    pypi_0    pypi
pycodestyle               2.5.0                      py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.4.2                    pypi_0    pypi
pyparsing                 2.4.6                      py_0    conda-forge
pyproj                    2.4.2.post1      py36hf8af742_1    conda-forge
pytest                    5.4.1                    pypi_0    pypi
pytest-cov                2.7.1                    pypi_0    pypi
pytest-vcr                1.0.2                    pypi_0    pypi
python                    3.6.7             h4285619_1006    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywavelets                1.1.1            py36h3b54f70_0    conda-forge
pyyaml                    5.1.2                    pypi_0    pypi
rasterio                  1.1.2            py36he71f6a4_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.22.0                   pypi_0    pypi
rtree                     0.9.3            py36h7b0cdae_0    conda-forge
scikit-image              0.16.2           py36h4f17bb1_0    conda-forge
scipy                     1.4.1            py36h82752d6_0    conda-forge
setuptools                45.0.0                   py36_1    conda-forge
shapely                   1.6.4           py36h999ffa5_1007    conda-forge
six                       1.14.0                   py36_0    conda-forge
snowballstemmer           2.0.0                    pypi_0    pypi
snuggs                    1.4.7                      py_0    conda-forge
sphinx                    2.4.0                    pypi_0    pypi
sphinx-autobuild          0.7.1                    pypi_0    pypi
sphinx-gallery            0.5.0                    pypi_0    pypi
sphinx-rtd-theme          0.4.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.1                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.1                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.2                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.2                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.3                    pypi_0    pypi
sqlite                    3.30.1               h93121df_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tiledb                    1.7.0                hd5e958f_2    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
toml                      0.10.0                   pypi_0    pypi
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py36h0b31af3_0    conda-forge
tox                       3.14.6                   pypi_0    pypi
tzcode                    2019a             h01d97ff_1002    conda-forge
urllib3                   1.25.6                   pypi_0    pypi
vcrpy                     2.1.0                    pypi_0    pypi
virtualenv                16.7.7                   pypi_0    pypi
watchdog                  0.9.0                    pypi_0    pypi
wcwidth                   0.1.7                    pypi_0    pypi
wheel                     0.33.6                   py36_0    conda-forge
wrapt                     1.11.2                   pypi_0    pypi
xerces-c                  3.2.2             hbda6038_1004    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
yarl                      1.3.0                    pypi_0    pypi
zipp                      0.6.0                    pypi_0    pypi
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                he7fca8b_1    conda-forge

```
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
(earthpy-dev) CIRES-EL-LM-020:earthpy leahwasser$ conda list
# packages in environment at /Users/leahwasser/miniconda3/envs/earthpy-dev:
#
# Name                    Version                   Build  Channel
affine                    2.3.0                      py_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
argh                      0.26.2                py37_1001    conda-forge
attrs                     19.3.0                     py_0    conda-forge
babel                     2.8.0                      py_0    conda-forge
boost-cpp                 1.72.0               hdf9ef73_0    conda-forge
brotlipy                  0.7.0           py37h9bfed18_1000    conda-forge
bumpversion               0.5.3                   py_1001    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cairo                     1.16.0            hec6a9b0_1003    conda-forge
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
cffi                      1.14.0           py37h356ff06_0    conda-forge
cfgv                      3.1.0                      py_0    conda-forge
cfitsio                   3.470                h35c4aa5_3    conda-forge
chardet                   3.0.4           py37hc8dfbb8_1006    conda-forge
click                     7.1.1              pyh8c360ce_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.3.0                      py_0    conda-forge
codecov                   2.0.20             pyh9f0ad1d_0    conda-forge
coverage                  5.1              py37h9bfed18_0    conda-forge
cryptography              2.9.2            py37he655712_0    conda-forge
curl                      7.69.1               h2d98d24_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.10.1           py37h0b31af3_0    conda-forge
dask-core                 2.15.0                     py_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
docutils                  0.16             py37hc8dfbb8_1    conda-forge
editdistance              0.5.3            py37h570ac47_0    conda-forge
expat                     2.2.9                h4a8c4bd_2    conda-forge
filelock                  3.0.10                     py_0    conda-forge
fiona                     1.8.13           py37he71f6a4_0    conda-forge
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.10.1               h8da9a1a_0    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
gdal                      3.0.4            py37h08e9697_8    conda-forge
geopandas                 0.7.0                      py_1    conda-forge
geos                      3.8.1                h4a8c4bd_0    conda-forge
geotiff                   1.5.1               hd8796ba_10    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.2.1                h0b31af3_2    conda-forge
glib                      2.64.2               h577aef8_0    conda-forge
hdf4                      4.2.13            h84186c3_1003    conda-forge
hdf5                      1.10.6          nompi_h3e39495_100    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
identify                  1.4.14             pyh9f0ad1d_0    conda-forge
idna                      2.9                        py_1    conda-forge
imageio                   2.8.0                      py_0    conda-forge
imagesize                 1.2.0                      py_0    conda-forge
importlib-metadata        1.6.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
kealib                    1.4.13               h40102fb_1    conda-forge
kiwisolver                1.2.0            py37ha1cc60f_0    conda-forge
krb5                      1.17.1               h1752a42_0    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libcurl                   7.69.1               hc0b9707_0    conda-forge
libcxx                    10.0.0               h1af66ff_2    conda-forge
libdap4                   3.20.6               h8c15375_0    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgdal                   3.0.4                h1772500_8    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h0b31af3_1006    conda-forge
libkml                    1.3.0             h169b8f9_1011    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libnetcdf                 4.7.4           nompi_ha11d67f_102    conda-forge
libopenblas               0.3.9                h3d69b6c_0    conda-forge
libpng                    1.6.37               hbbe82c9_1    conda-forge
libpq                     12.2                 h489d428_1    conda-forge
libspatialindex           1.9.3                h4a8c4bd_3    conda-forge
libspatialite             4.3.0a            h658e6c1_1038    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.1.0                h2ae36a8_6    conda-forge
libwebp-base              1.1.0                h0b31af3_3    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
livereload                2.6.1                      py_0    conda-forge
llvm-openmp               10.0.0               h28b9765_0    conda-forge
lz4-c                     1.9.2                h4a8c4bd_0    conda-forge
markupsafe                1.1.1            py37h9bfed18_1    conda-forge
matplotlib                3.2.1                         0    conda-forge
matplotlib-base           3.2.1            py37hddda452_0    conda-forge
more-itertools            8.2.0                      py_0    conda-forge
munch                     2.5.0                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
networkx                  2.4                        py_1    conda-forge
nodeenv                   1.3.5                      py_0    conda-forge
numpy                     1.18.1           py37h7687784_1    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h254dc36_3    conda-forge
openssl                   1.1.1g               h0b31af3_0    conda-forge
packaging                 20.1                       py_0    conda-forge
pandas                    1.0.3            py37h94625e5_1    conda-forge
pathtools                 0.1.2                      py_1    conda-forge
pcre                      8.44                 h4a8c4bd_0    conda-forge
pillow                    7.1.2            py37hfd78ece_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
pluggy                    0.13.0                   py37_0    conda-forge
poppler                   0.87.0               h3232a60_1    conda-forge
poppler-data              0.4.9                         1    conda-forge
port-for                  0.4                        py_1    conda-forge
postgresql                12.2                 h62ab893_1    conda-forge
pre-commit                2.3.0            py37hc8dfbb8_0    conda-forge
proj                      7.0.0                hbce2d5c_3    conda-forge
py                        1.8.1                      py_0    conda-forge
pycparser                 2.20                       py_0    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    2.6.0            py37hbd4ead9_1    conda-forge
pysocks                   1.7.1            py37hc8dfbb8_1    conda-forge
pytest                    5.4.1            py37hc8dfbb8_0    conda-forge
pytest-cov                2.8.1                      py_0    conda-forge
python                    3.7.6           h90870a6_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytz                      2019.3                     py_0    conda-forge
pywavelets                1.1.1            py37h10e2902_1    conda-forge
pyyaml                    5.3.1            py37h9bfed18_0    conda-forge
rasterio                  1.1.3            py37he71f6a4_0    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
requests                  2.23.0             pyh8c360ce_2    conda-forge
rtree                     0.9.4            py37h8526d28_1    conda-forge
scikit-image              0.16.2           py37h4f17bb1_0    conda-forge
scipy                     1.4.1            py37hce1b9e5_3    conda-forge
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
shapely                   1.7.0            py37hfcf0db4_3    conda-forge
six                       1.14.0                     py_1    conda-forge
snowballstemmer           2.0.0                      py_0    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sphinx                    3.0.3                      py_0    conda-forge
sphinx-autobuild          0.7.1                      py_2    conda-forge
sphinx_rtd_theme          0.4.3                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.2                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.3                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.3                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.4                      py_0    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tiledb                    1.7.7                h84aa2a7_1    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
toml                      0.10.0                     py_0    conda-forge
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.4            py37h9bfed18_1    conda-forge
tox                       3.14.6           py37hc8dfbb8_0    conda-forge
tzcode                    2020a                h0b31af3_0    conda-forge
urllib3                   1.25.9                     py_0    conda-forge
virtualenv                16.7.5                     py_0    conda-forge
watchdog                  0.10.2           py37h0b31af3_0    conda-forge
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xerces-c                  3.2.2             h8f8adb3_1004    conda-forge
xz                        5.2.5                h0b31af3_0    conda-forge
yaml                      0.2.4                h0b31af3_0    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                h4b3e974_3    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
    active env location : /Users/leahwasser/miniconda3/envs/earthpy-dev
            shell level : 2
       user config file : /Users/leahwasser/.condarc
 populated config files : /Users/leahwasser/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __osx=10.14.6
       base environment : /Users/leahwasser/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/leahwasser/miniconda3/pkgs
                          /Users/leahwasser/.conda/pkgs
       envs directories : /Users/leahwasser/miniconda3/envs
                          /Users/leahwasser/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Darwin/18.7.0 OSX/10.14.6
                UID:GID : 502:20
             netrc file : None
           offline mode : False
```
</details>

I'm happy to try anything else that might help with troubleshooting. i'm just not sure what else to try! I hope all is well.

**Comment by djhoese** [comment]
I'm also seeing this on travis:

```
>   from rasterio._base import gdal_version
E   ImportError: dlopen(/Users/travis/miniconda/envs/test/lib/python3.8/site-packages/rasterio/_base.cpython-38-darwin.so, 2): Symbol not found: _crc32
E     Referenced from: /Users/travis/miniconda/envs/test/lib/libgdal.26.dylib
E     Expected in: /Users/travis/miniconda/envs/test/lib/libcfitsio.8.dylib
E    in /Users/travis/miniconda/envs/test/lib/libgdal.26.dylib
```

Relevant travis job: https://travis-ci.org/github/pytroll/satpy/jobs/680364670

**Comment by lwasser** [comment]
Oh interesting. And you are on python 3.8. Ive tested on 3.6 and 3.7 so it is not the python version!

I downgraded several packages too including gdal to see if I could figure out which upgrade broke things but to no avail.

**Comment by djhoese** [comment]
Looks like cfitsio had a new release a couple days ago: https://github.com/conda-forge/cfitsio-feedstock

@lwasser Could you try forcing the version to something older. I think this should work:

```
conda install cfitsio=3.470=2
```

**Comment by lwasser** [comment]
@djhoese PROGRESS!

i ran this
`conda install -c conda-forge cfitsio=3.470=h84d2f63_2`

and pytest is running perfectly now! 

in my broken build i have this:
`cfitsio                   3.470                h35c4aa5_3`

It was funny because i thought that package might be the cuprit but i saw the same version numbers missing the fact that the build is different. So is the solution for now (temporarily) to downgrade our builds to that working build. And in the future perhaps this build will resolve properly?

**Comment by lwasser** [comment]
@djhoese given this is open in the cfitsio repo, should i close here? just wanted to check that there is nothing to do with rasterio before closing. seems to be on the way to being fixed in the other repo.

**Comment by ocefpaf** [comment]
> wave hi there @ocefpaf !! me, yet again. i'm running into some issues with rasterio (i think) on MAC.
Essentially it's throwing errors for our earthpy build: example

Sorry, just got back to work today. Looks like people already found a way forward to fix this.

> @djhoese given this is open in the cfitsio repo, should i close here? just wanted to check that there is nothing to do with rasterio before closing. seems to be on the way to being fixed in the other repo.

Yes please. Thanks for the but report!

**Comment by lwasser** [comment]
👋 @ocefpaf no worries!! and thank you!! 

yes i think we did some detective work and it's cfitsio. i'll close for now :) but again happy to test when its needed!!
