### ISSUE TITLE
Installing rasterio doesn't install certifi dependency 

### ISSUE THREAD

**Issue by robintw** [conda-forge/rasterio-feedstock#224]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I have created a new conda environment and just installed `rasterio`, using a command like

```
conda create -n test rasterio
```

When I then try to run the `rio info` command, I get the following error:

```
Warning: entry point could not be loaded. Contact its author for help.


Traceback (most recent call last):
  File "C:\Users\rwilson3\Documents\mambaforge\envs\test2\lib\site-packages\click_plugins\core.py", line 37, in decorator
    group.add_command(entry_point.load())
  File "C:\Users\rwilson3\Documents\mambaforge\envs\test2\lib\site-packages\pkg_resources\__init__.py", line 2449, in load
    self.require(*args, **kwargs)
  File "C:\Users\rwilson3\Documents\mambaforge\envs\test2\lib\site-packages\pkg_resources\__init__.py", line 2472, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "C:\Users\rwilson3\Documents\mambaforge\envs\test2\lib\site-packages\pkg_resources\__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'certifi' distribution was not found and is required by the application
```

When I then run `conda install certifi` and try `rio info` again, it works fine.

This suggests that the `certifi` dependency hasn't been specified correctly in this conda package.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at C:\Users\rwilson3\Documents\mambaforge\envs\test2:
#
# Name                    Version                   Build  Channel
affine                    2.3.0                      py_0    conda-forge
attrs                     21.2.0             pyhd8ed1ab_0    conda-forge
boost-cpp                 1.74.0               h5b4e17d_4    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2021.5.30            h5b45459_0    conda-forge
cairo                     1.16.0            hb19e0ff_1008    conda-forge
certifi                   2021.5.30        py39hcbf5309_0    conda-forge
cfitsio                   3.470                h0af3d06_7    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_0    conda-forge
curl                      7.79.1               h789b8ee_1    conda-forge
expat                     2.4.1                h39d44d4_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.13.1            h1989441_1005    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
freexl                    1.0.6                ha8e266a_0    conda-forge
geos                      3.9.1                h39d44d4_2    conda-forge
geotiff                   1.7.0                h350af67_3    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.12.1          nompi_h2a0e4a3_100    conda-forge
icu                       68.1                 h0e60522_0    conda-forge
intel-openmp              2021.3.0          h57928b3_3372    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jpeg                      9d                   h8ffe710_0    conda-forge
kealib                    1.4.14               h8995ca9_3    conda-forge
krb5                      1.19.2               hbae68bd_2    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      2.2.1                h0e60522_0    conda-forge
libblas                   3.9.0              11_win64_mkl    conda-forge
libcblas                  3.9.0              11_win64_mkl    conda-forge
libcurl                   7.79.1               h789b8ee_1    conda-forge
libdeflate                1.7                  h8ffe710_5    conda-forge
libffi                    3.4.2                h0e60522_4    conda-forge
libgdal                   3.3.2                h08edb8f_4    conda-forge
libglib                   2.68.4               h3be07f2_1    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
libkml                    1.3.0             h9859afa_1014    conda-forge
liblapack                 3.9.0              11_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h1cc8e9d_101    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libpq                     13.3                 hfcc5ef8_0    conda-forge
librttopo                 1.1.0                hb340de5_6    conda-forge
libspatialite             5.0.1                h6a90f17_9    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtiff                   4.3.0                h0c97f57_1    conda-forge
libwebp-base              1.2.1                h8ffe710_0    conda-forge
libxml2                   2.9.12               hf5bbc77_0    conda-forge
libzip                    1.8.0                hfed4ece_1    conda-forge
libzlib                   1.2.11            h8ffe710_1013    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
mkl                       2021.3.0           hb70f87d_564    conda-forge
numpy                     1.21.2           py39h6635163_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openssl                   1.1.1l               h8ffe710_0    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pip                       21.2.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
poppler                   21.09.0              h24fffdf_3    conda-forge
poppler-data              0.4.11               hd8ed1ab_0    conda-forge
postgresql                13.3                 h1c22c4f_0    conda-forge
proj                      8.1.1                h1cfcee9_2    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
python                    3.9.7           h7840368_3_cpython    conda-forge
python_abi                3.9                      2_cp39    conda-forge
rasterio                  1.2.9            py39h20dd13d_1    conda-forge
setuptools                58.0.4           py39hcbf5309_2    conda-forge
snuggs                    1.4.7                      py_0    conda-forge
sqlite                    3.36.0               h8ffe710_2    conda-forge
tbb                       2021.3.0             h2d74725_0    conda-forge
tiledb                    2.3.4                h78dabda_0    conda-forge
tk                        8.6.11               h8ffe710_1    conda-forge
tzdata                    2021b                he74cb21_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
vc                        14.2                 hb210afc_5    conda-forge
vs2015_runtime            14.29.30037          h902a5da_5    conda-forge
wheel                     0.37.0             pyhd8ed1ab_1    conda-forge
xerces-c                  3.2.3                h0e60522_2    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
zlib                      1.2.11            h8ffe710_1013    conda-forge
zstd                      1.5.0                h6255e5f_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : test2
    active env location : C:\Users\rwilson3\Documents\mambaforge\envs\test2
            shell level : 1
       user config file : C:\Users\rwilson3\.condarc
 populated config files : C:\Users\rwilson3\Documents\mambaforge\.condarc
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.9.7.final.0
       virtual packages : __win=0=0
                          __archspec=1=x86_64
       base environment : C:\Users\rwilson3\Documents\mambaforge  (writable)
      conda av data dir : C:\Users\rwilson3\Documents\mambaforge\etc\conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : C:\Users\rwilson3\Documents\mambaforge\pkgs
                          C:\Users\rwilson3\.conda\pkgs
                          C:\Users\rwilson3\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\rwilson3\Documents\mambaforge\envs
                          C:\Users\rwilson3\.conda\envs
                          C:\Users\rwilson3\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.10.3 requests/2.26.0 CPython/3.9.7 Windows/10 Windows/10.0.19043
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by xylar** [comment]
Sorry about that!  `certifi` has been a dependency since 1.2.0 but somehow we missed it!
