### ISSUE TITLE
rasterio can't find libgdal.so.36  when gdal, libgdal, and rasterio installed via conda-forge channel

### ISSUE THREAD

**Issue by rbavery** [conda-forge/rasterio-feedstock#324]
### Solution to issue cannot be found in the documentation.

- [x] I checked the documentation.

### Issue

I'm trying to use this environment to read a stac-geoparquet with the new GTI driver that comes with gdal 3.10

```
conda create -n test python=3.11 rasterio==1.4.2 gdal==3.10 libgdal==3.10
```

then pip install `pip install stacrs`

I can use the GTI driver with a FlatGeoBuf

```python
import xarray
ds = xarray.open_dataset("GTI:https://github.com/mdsumner/gti/raw/refs/heads/main/inst/extdata/tmerc_seaice.fgb", engine = "rasterio")
```

but not stac-geoparquet. idk why, but rasterio looks for the wrong libgdal.so.35, I have libgdal.so.36

```python
from datetime import datetime, timedelta
import stacrs
import xarray

def convert_to_iso_datetime_range(simple_date_range):
    start_date_str, end_date_str = simple_date_range.split('/')
    start_date = datetime.strptime(start_date_str, "%Y-%m-%d")
    end_date = datetime.strptime(end_date_str, "%Y-%m-%d")
    start_date_iso = start_date.strftime("%Y-%m-%dT%H:%M:%S.%fZ")[:-3] + "Z"
    end_date_iso = (end_date - timedelta(seconds=1)).strftime("%Y-%m-%dT%H:%M:%S.%fZ")[:-3] + "Z"
    return f"{start_date_iso}/{end_date_iso}"

max_cloud_cover = 15
max_nodata_percent = 15
query_args = {
            "eo:cloud_cover": {"lt": max_cloud_cover},
            "s2:nodata_pixel_percentage": {"lt": max_nodata_percent},
        }
simple_date_range = "2023-01-01/2024-01-01"
iso_datetime_range = convert_to_iso_datetime_range(simple_date_range)
collection_id = "sentinel-2-c1-l2a"
catalog = "https://earth-search.aws.element84.com/v1"
lon, lat = -111.760826, 34.871002

# stack args
assets=["rededge1", "rededge2", "rededge3", "nir", "swir16", "swir22"]
rescale=False
xy_coords="center"
stack_id = "grid:code"
stack_dim = "time"

stacrs.search_to(
    "items.parquet",
    catalog,
    collections=collection_id,
    intersects={"type": "Point", "coordinates": [lon, lat]},
    sortby="-properties.datetime",
    max_items=100,
    datetime=iso_datetime_range,
    query=query_args
)

ds = xarray.open_dataset("GTI:/absolute/path/to/items.parquet", engine = "rasterio")
```

```
ls  ls /home/rave/miniforge3/envs/test/lib

libgdal.so.36 
```

### Installed packages

```shell
-> % conda list
# packages in environment at /home/rave/miniforge3/envs/test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
affine                    2.4.0              pyhd8ed1ab_0    conda-forge
aom                       3.9.1                hac33072_0    conda-forge
attrs                     24.2.0             pyh71513ae_0    conda-forge
aws-c-auth                0.8.0               hb88c0a9_10    conda-forge
aws-c-cal                 0.8.0                hecf86a2_2    conda-forge
aws-c-common              0.10.3               hb9d3cd8_0    conda-forge
aws-c-compression         0.3.0                hf42f96a_2    conda-forge
aws-c-event-stream        0.5.0                h1ffe551_7    conda-forge
aws-c-http                0.9.1                hab05fe4_2    conda-forge
aws-c-io                  0.15.2               hdeadb07_2    conda-forge
aws-c-mqtt                0.11.0               h7bd072d_8    conda-forge
aws-c-s3                  0.7.1                h3a84f74_3    conda-forge
aws-c-sdkutils            0.2.1                hf42f96a_1    conda-forge
aws-checksums             0.2.2                hf42f96a_1    conda-forge
aws-crt-cpp               0.29.4               h21d7256_1    conda-forge
aws-sdk-cpp               1.11.449             h1a02111_2    conda-forge
azure-core-cpp            1.14.0               h5cfcd09_0    conda-forge
azure-identity-cpp        1.10.0               h113e628_0    conda-forge
azure-storage-blobs-cpp   12.13.0              h3cf044e_1    conda-forge
azure-storage-common-cpp  12.8.0               h736e048_1    conda-forge
blosc                     1.21.6               hef167b5_0    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
c-ares                    1.34.3               heb4867d_0    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
cairo                     1.18.0               hebfffa5_3    conda-forge
capnproto                 1.0.2                h766bdaa_3    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cfitsio                   4.4.1                ha728647_2    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.7.2              pyhd8ed1ab_1    conda-forge
cyrus-sasl                2.1.27               h54b06d7_7    conda-forge
dav1d                     1.2.1                hd590300_0    conda-forge
fmt                       11.0.2               h434a139_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_3    conda-forge
fontconfig                2.15.0               h7e30c49_1    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
freexl                    2.0.0                h743c826_0    conda-forge
gdal                      3.10.0          py311h35e7c94_1    conda-forge
geos                      3.13.0               h5888daf_0    conda-forge
geotiff                   1.7.3                h77b800c_3    conda-forge
giflib                    5.2.2                hd590300_0    conda-forge
hdf4                      4.2.15               h2a13503_7    conda-forge
hdf5                      1.14.3          nompi_hdf9ad27_105    conda-forge
icu                       75.1                 he02047a_0    conda-forge
json-c                    0.18                 h6688a6e_0    conda-forge
kealib                    1.5.3                hf8d3e68_2    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.21.3               h659f571_0    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.43                 h712a8e2_2    conda-forge
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20240722.0      cxx17_h5888daf_1    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libarchive                3.7.4                hfca40fe_0    conda-forge
libavif16                 1.1.1                h1909e37_2    conda-forge
libblas                   3.9.0           25_linux64_openblas    conda-forge
libcblas                  3.9.0           25_linux64_openblas    conda-forge
libcrc32c                 1.1.2                h9c3ff4c_0    conda-forge
libcurl                   8.10.1               hbbe4b11_0    conda-forge
libde265                  1.0.15               h00ab1b0_0    conda-forge
libdeflate                1.22                 hb9d3cd8_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 hd590300_2    conda-forge
libexpat                  2.6.4                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.2.0               h77fa898_1    conda-forge
libgcc-ng                 14.2.0               h69a702a_1    conda-forge
libgdal                   3.10.0               ha770c72_1    conda-forge
libgdal-core              3.10.0               hef9eae6_1    conda-forge
libgdal-fits              3.10.0               he1674de_1    conda-forge
libgdal-grib              3.10.0               ha360943_1    conda-forge
libgdal-hdf4              3.10.0               h380f24e_1    conda-forge
libgdal-hdf5              3.10.0               hefe6d7a_1    conda-forge
libgdal-jp2openjpeg       3.10.0               h9fdfae1_1    conda-forge
libgdal-kea               3.10.0               h38e673a_1    conda-forge
libgdal-netcdf            3.10.0               hba670d9_1    conda-forge
libgdal-pdf               3.10.0               h697c966_1    conda-forge
libgdal-pg                3.10.0               h5cc4e75_1    conda-forge
libgdal-postgisraster     3.10.0               h5cc4e75_1    conda-forge
libgdal-tiledb            3.10.0               hec57c18_1    conda-forge
libgdal-xls               3.10.0               h1e14832_1    conda-forge
libgfortran               14.2.0               h69a702a_1    conda-forge
libgfortran-ng            14.2.0               h69a702a_1    conda-forge
libgfortran5              14.2.0               hd5240d6_1    conda-forge
libglib                   2.82.2               h2ff4ddf_0    conda-forge
libgomp                   14.2.0               h77fa898_1    conda-forge
libgoogle-cloud           2.31.0               h804f50b_0    conda-forge
libgoogle-cloud-storage   2.31.0               h0121fbd_0    conda-forge
libgrpc                   1.67.1               hc2c308b_0    conda-forge
libheif                   1.18.2          gpl_hffcb242_100    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
libkml                    1.3.0             hf539b9f_1021    conda-forge
liblapack                 3.9.0           25_linux64_openblas    conda-forge
libnetcdf                 4.9.2           nompi_h135f659_114    conda-forge
libnghttp2                1.64.0               h161d5f1_0    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libntlm                   1.4               h7f98852_1002    conda-forge
libopenblas               0.3.28          pthreads_h94d23a6_1    conda-forge
libpng                    1.6.44               hadc24fc_0    conda-forge
libpq                     17.1                 h04577a9_0    conda-forge
libprotobuf               5.28.2               h5b01275_0    conda-forge
libre2-11                 2024.07.02           hbbce691_1    conda-forge
librttopo                 1.1.0               h97f6797_17    conda-forge
libspatialite             5.1.0               h1b4f908_11    conda-forge
libsqlite                 3.47.0               hadc24fc_1    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx                 14.2.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.2.0               h4852527_1    conda-forge
libtiff                   4.7.0                he137b08_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.17.0               h8a09558_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.13.5               hb346dea_0    conda-forge
libxslt                   1.1.39               h76b75d6_0    conda-forge
libzip                    1.11.2               h6991a6a_0    conda-forge
libzlib                   1.3.1                hb9d3cd8_2    conda-forge
lz4-c                     1.9.4                hcb278e6_0    conda-forge
lzo                       2.10              hd590300_1001    conda-forge
minizip                   4.0.7                h401b404_0    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
nspr                      4.36                 h5888daf_0    conda-forge
nss                       3.106                hdf54f9c_0    conda-forge
numpy                     2.1.3           py311h71ddf71_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openldap                  2.6.8                hedd0468_0    conda-forge
openssl                   3.4.0                hb9d3cd8_0    conda-forge
pcre2                     10.44                hba22ea6_2    conda-forge
pip                       24.3.1             pyh8b19718_0    conda-forge
pixman                    0.43.2               h59595ed_0    conda-forge
poppler                   24.08.0              h47131b8_1    conda-forge
poppler-data              0.4.12               hd8ed1ab_0    conda-forge
postgresql                17.1                 h1122569_0    conda-forge
proj                      9.5.0                h12925eb_0    conda-forge
pthread-stubs             0.4               hb9d3cd8_1002    conda-forge
pyparsing                 3.2.0              pyhd8ed1ab_1    conda-forge
python                    3.11.10         hc5c86c4_3_cpython    conda-forge
python_abi                3.11                    5_cp311    conda-forge
rasterio                  1.4.2           py311h5394301_1    conda-forge
rav1e                     0.6.6                he8a937b_2    conda-forge
re2                       2024.07.02           h77b4e00_1    conda-forge
readline                  8.2                  h8228510_1    conda-forge
s2n                       1.5.9                h0fd0ee4_0    conda-forge
setuptools                75.5.0             pyhff2d567_0    conda-forge
snappy                    1.2.1                ha2e4443_0    conda-forge
snuggs                    1.4.7              pyhd8ed1ab_1    conda-forge
spdlog                    1.14.1               hed91bc2_1    conda-forge
sqlite                    3.47.0               h9eae976_1    conda-forge
svt-av1                   2.3.0                h5888daf_0    conda-forge
tiledb                    2.26.2              h84bbdfb_10    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzcode                    2024b                hb9d3cd8_0    conda-forge
tzdata                    2024b                hc8b5060_0    conda-forge
uriparser                 0.9.8                hac33072_0    conda-forge
wheel                     0.45.0             pyhd8ed1ab_0    conda-forge
x265                      3.5                  h924138e_3    conda-forge
xerces-c                  3.2.5                h988505b_2    conda-forge
xorg-libice               1.1.1                hb9d3cd8_1    conda-forge
xorg-libsm                1.2.4                he73a12e_1    conda-forge
xorg-libx11               1.8.10               h4f16b4b_0    conda-forge
xorg-libxau               1.0.11               hb9d3cd8_1    conda-forge
xorg-libxdmcp             1.1.5                hb9d3cd8_0    conda-forge
xorg-libxext              1.3.6                hb9d3cd8_0    conda-forge
xorg-libxrender           0.9.11               hb9d3cd8_1    conda-forge
xorg-xorgproto            2024.1               hb9d3cd8_1    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.3.1                hb9d3cd8_2    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

### Environment info

```shell
rave@studio2 [12:24:40] [~]
-> % conda info

     active environment : test
    active env location : /home/rave/miniforge3/envs/test
            shell level : 2
       user config file : /home/rave/.condarc
 populated config files : /home/rave/miniforge3/.condarc
          conda version : 24.7.1
    conda-build version : not installed
         python version : 3.11.6.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.7.1=0
                          __cuda=12.2=0
                          __glibc=2.35=0
                          __linux=5.15.167.4=0
                          __unix=0=0
       base environment : /home/rave/miniforge3  (writable)
      conda av data dir : /home/rave/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/rave/miniforge3/pkgs
                          /home/rave/.conda/pkgs
       envs directories : /home/rave/miniforge3/envs
                          /home/rave/.conda/envs
               platform : linux-64
             user-agent : conda/24.7.1 requests/2.31.0 CPython/3.11.6 Linux/5.15.167.4-microsoft-standard-WSL2 ubuntu/22.04.2 glibc/2.35 solver/libmamba conda-libmamba-solver/23.11.0 libmambapy/1.5.8
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by weiji14** [comment]
Hmm, I'm getting a compile error when running `pip install stacrs`, not sure why it's not picking up one of the binary wheels at https://pypi.org/project/stacrs/0.2.2/#files:

<details>

```
Collecting stacrs==0.2.2
  Using cached stacrs-0.2.2.tar.gz (1.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: stacrs
  Building wheel for stacrs (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for stacrs (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [334 lines of output]
      Running `maturin pep517 build-wheel -i /home/user/mambaforge/envs/test/bin/python --compatibility off`
      🔗 Found pyo3 bindings
      🐍 Found CPython 3.11 at /home/user/mambaforge/envs/test/bin/python
      📡 Using build options features from pyproject.toml
         Compiling proc-macro2 v1.0.89
         ...
         Compiling geoarrow v0.3.0
      error[E0275]: overflow evaluating the requirement `<impl GeometryTrait<T = f64> as geo_traits::geometry::GeometryTrait>::GeometryCollection<'_>: geo_traits::geometry_collection::GeometryCollectionTrait`
          |
          = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`geoarrow`)
      note: required for `GeometryCollectionIterator<'_, f64, <... as GeometryCollectionTrait>::ItemType<'_>, ...>` to implement `Iterator`
         --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/geoarrow-0.3.0/src/geo_traits/iterator.rs:39:15
          |
      37  |                   ItemType: 'a + $item_trait<T = T>,
          |                                              ----- unsatisfied trait bound introduced here
      38  |                   G: $self_trait<T = T, ItemType<'a> = ItemType>,
      39  |               > Iterator for $struct_name<'a, T, ItemType, G>
          |                 ^^^^^^^^     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      ...
      109 | / impl_iterator!(
      110 | |     GeometryCollectionIterator,
      111 | |     GeometryCollectionTrait,
      112 | |     GeometryTrait,
      113 | |     geometry_unchecked
      114 | | );
          | |_- in this macro invocation
          = note: required for `GeometryCollectionIterator<'_, f64, <... as GeometryCollectionTrait>::ItemType<'_>, ...>` to implement `IntoIterator`
          = note: the full name for the type has been written to '/tmp/pip-install-qejaxs79/stacrs_1c740345c7a64a849c43837b6c219da2/target/release/deps/geoarrow-60c46f17e7ced68a.long-type-9005216031339014866.txt'
          = note: consider using `--verbose` to print the full type name to the console
          = note: the full name for the type has been written to '/tmp/pip-install-qejaxs79/stacrs_1c740345c7a64a849c43837b6c219da2/target/release/deps/geoarrow-60c46f17e7ced68a.long-type-9005216031339014866.txt'
          = note: consider using `--verbose` to print the full type name to the console
          = note: this error originates in the macro `impl_iterator` (in Nightly builds, run with -Z macro-backtrace for more info)

      For more information about this error, try `rustc --explain E0275`.
      error: could not compile `geoarrow` (lib) due to 1 previous error
      warning: build failed, waiting for other jobs to finish...
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_ENVIRONMENT_SIGNATURE="cpython-3.11-64bit" PYO3_PYTHON="/home/user/mambaforge/envs/test/bin/python" PYTHON_SYS_EXECUTABLE="/home/user/mambaforge/envs/test/bin/python" "cargo" "rustc" "--features" "pyo3/extension-module" "--message-format" "json-render-diagnostics" "--manifest-path" "/tmp/pip-install-qejaxs79/stacrs_1c740345c7a64a849c43837b6c219da2/python/Cargo.toml" "--release" "--lib"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/home/user/mambaforge/envs/test/bin/python', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for stacrs
Failed to build stacrs
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (stacrs)
```

</details>

I'll try and see if I can fix the compile errors (maybe I'm using an incompatible version of rustc), so that I can reproduce this properly. But just to answer quickly, it might be best to package stac-rs on conda-forge to handle GDAL incompatibility issues.

**Comment by weiji14** [comment]
Managed to compile after downgrading my rustc version from 1.82 to 1.80 using `rustup default 1.80`. I also needed to install a few more packages:

```bash
conda install -c conda-forge rioxarray libgdal-arrow-parquet
```

and then I got this error:

```python-traceback
Traceback (most recent call last):
  File "/home/user/mambaforge/envs/test/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 211, in _acquire_with_cache_info
    file = self._cache[self._key]
           ~~~~~~~~~~~^^^^^^^^^^^
  File "/home/user/mambaforge/envs/test/lib/python3.11/site-packages/xarray/backends/lru_cache.py", line 56, in __getitem__
    value = self._cache[key]
            ~~~~~~~~~~~^^^^^
KeyError: [<function open at 0x7f0f9ac28b80>, ('GTI:/home/user/items.parquet',), 'r', (('sharing', False),), 'ae2c44bb-1e02-4c90-a3e0-aacef4e57f5a']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "rasterio/_base.pyx", line 310, in rasterio._base.DatasetBase.__init__
  File "rasterio/_base.pyx", line 221, in rasterio._base.open_dataset
  File "rasterio/_err.pyx", line 359, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_AppDefinedError: Cannot find field location

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/mambaforge/envs/test/lib/python3.11/site-packages/xarray/backends/api.py", line 671, in open_dataset
    backend_ds = backend.open_dataset(
                 ^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/test/lib/python3.11/site-packages/rioxarray/xarray_plugin.py", line 58, in open_dataset
    rds = _io.open_rasterio(
          ^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/test/lib/python3.11/site-packages/rioxarray/_io.py", line 1128, in open_rasterio
    riods = manager.acquire()
            ^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/test/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 193, in acquire
    file, _ = self._acquire_with_cache_info(needs_lock)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/test/lib/python3.11/site-packages/xarray/backends/file_manager.py", line 217, in _acquire_with_cache_info
    file = self._opener(*self._args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/test/lib/python3.11/site-packages/rasterio/env.py", line 463, in wrapper
    return f(*args, **kwds)
           ^^^^^^^^^^^^^^^^
  File "/home/user/mambaforge/envs/test/lib/python3.11/site-packages/rasterio/__init__.py", line 355, in open
    dataset = DatasetReader(path, driver=driver, sharing=sharing, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "rasterio/_base.pyx", line 312, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: Cannot find field location
```

Was this the error you were getting? Doesn't seem related to not finding libgdal.

**Comment by rbavery** [comment]
WOOPS sorry for the bad mre. Missed those dependencies. I get the same error and I don't think this is a rasterio/gdal packaging issue. I think it's probably some incompatibility between the geoparquet produced by `stacrs` and the GDAL 3.10 GTI driver expecting certain field names.

The issue with libgdal not being found seems specific to m[y use of pixi to set up the conda environment](https://github.com/rbavery/odc-stac-global). I think some environment variables are not being correctly set up to discover the correct GDAL potentially. in any case doesn't seem like an issue with packaging so closing

**Comment by weiji14** [comment]
FYI @rbavery, there's a [`stacrs` package on conda-forge](https://github.com/conda-forge/stacrs-feedstock) now.
