### ISSUE TITLE
Able to install incompatible environment of python=3.9 rasterio=1.4.0 gdal=3.10.0

### ISSUE THREAD

**Issue by akrherz** [conda-forge/rasterio-feedstock#325]
### Comment:

Spotted in my CI with pure conda-forge

```
$ mamba create -n dev python=3.9 rasterio=1.4.0 gdal=3.10.0
  + _libgcc_mutex                0.1  conda_forge          conda-forge        3kB
  + _openmp_mutex                4.5  2_gnu                conda-forge       24kB
  + affine                     2.4.0  pyhd8ed1ab_0         conda-forge     Cached
  + aom                        3.9.1  hac33072_0           conda-forge     Cached
  + attrs                     24.2.0  pyh71513ae_0         conda-forge     Cached
  + blosc                     1.21.6  hef167b5_0           conda-forge     Cached
  + bzip2                      1.0.8  h4bc722e_7           conda-forge     Cached
  + c-ares                    1.34.3  hb9d3cd8_1           conda-forge     Cached
  + ca-certificates        2024.8.30  hbcca054_0           conda-forge     Cached
  + certifi                2024.8.30  pyhd8ed1ab_0         conda-forge     Cached
  + click                      8.1.7  unix_pyh707e725_0    conda-forge     Cached
  + click-plugins              1.1.1  py_0                 conda-forge     Cached
  + cligj                      0.7.2  pyhd8ed1ab_1         conda-forge     Cached
  + dav1d                      1.2.1  hd590300_0           conda-forge     Cached
  + freexl                     2.0.0  h743c826_0           conda-forge     Cached
  + gdal                      3.10.0  py39hf75c608_2       conda-forge        2MB
  + geos                      3.13.0  h5888daf_0           conda-forge     Cached
  + geotiff                    1.7.3  h77b800c_3           conda-forge     Cached
  + giflib                     5.2.2  hd590300_0           conda-forge     Cached
  + icu                         75.1  he02047a_0           conda-forge     Cached
  + importlib-metadata         8.5.0  pyha770c72_0         conda-forge     Cached
  + json-c                      0.18  h6688a6e_0           conda-forge     Cached
  + keyutils                   1.6.1  h166bdaf_0           conda-forge     Cached
  + krb5                      1.21.3  h659f571_0           conda-forge     Cached
  + ld_impl_linux-64            2.43  h712a8e2_2           conda-forge     Cached
  + lerc                       4.0.0  h27087fc_0           conda-forge     Cached
  + libarchive                 3.7.7  hadbb8c3_0           conda-forge     Cached
  + libavif16                  1.1.1  h1909e37_2           conda-forge     Cached
  + libblas                    3.9.0  25_linux64_openblas  conda-forge       16kB
  + libcblas                   3.9.0  25_linux64_openblas  conda-forge       16kB
  + libcurl                   8.10.1  hbbe4b11_0           conda-forge     Cached
  + libde265                  1.0.15  h00ab1b0_0           conda-forge     Cached
  + libdeflate                  1.22  hb9d3cd8_0           conda-forge     Cached
  + libedit             3.1.20191231  he28a2e2_2           conda-forge     Cached
  + libev                       4.33  hd590300_2           conda-forge     Cached
  + libexpat                   2.6.4  h5888daf_0           conda-forge     Cached
  + libffi                     3.4.2  h7f98852_5           conda-forge     Cached
  + libgcc                    14.2.0  h77fa898_1           conda-forge     Cached
  + libgcc-ng                 14.2.0  h69a702a_1           conda-forge       54kB
  + libgdal-core              3.10.0  hef9eae6_2           conda-forge     Cached
  + libgfortran               14.2.0  h69a702a_1           conda-forge       54kB
  + libgfortran5              14.2.0  hd5240d6_1           conda-forge     Cached
  + libgomp                   14.2.0  h77fa898_1           conda-forge     Cached
  + libheif                   1.18.2  gpl_hffcb242_100     conda-forge     Cached
  + libiconv                    1.17  hd590300_2           conda-forge     Cached
  + libjpeg-turbo              3.0.0  hd590300_1           conda-forge     Cached
  + libkml                     1.3.0  hf539b9f_1021        conda-forge     Cached
  + liblapack                  3.9.0  25_linux64_openblas  conda-forge       16kB
  + libnghttp2                1.64.0  h161d5f1_0           conda-forge     Cached
  + libnsl                     2.0.1  hd590300_0           conda-forge     Cached
  + libopenblas               0.3.28  pthreads_h94d23a6_1  conda-forge     Cached
  + libpng                    1.6.44  hadc24fc_0           conda-forge     Cached
  + librttopo                  1.1.0  h97f6797_17          conda-forge     Cached
  + libspatialite              5.1.0  h1b4f908_11          conda-forge     Cached
  + libsqlite                 3.47.0  hadc24fc_1           conda-forge     Cached
  + libssh2                   1.11.1  hf672d98_0           conda-forge     Cached
  + libstdcxx                 14.2.0  hc0a3c3a_1           conda-forge     Cached
  + libstdcxx-ng              14.2.0  h4852527_1           conda-forge       54kB
  + libtiff                    4.7.0  he137b08_1           conda-forge     Cached
  + libuuid                   2.38.1  h0b41bf4_0           conda-forge     Cached
  + libwebp-base               1.4.0  hd590300_0           conda-forge     Cached
  + libxcrypt                 4.4.36  hd590300_1           conda-forge     Cached
  + libxml2                   2.13.5  hb346dea_0           conda-forge     Cached
  + libzlib                    1.3.1  hb9d3cd8_2           conda-forge     Cached
  + lz4-c                      1.9.4  hcb278e6_0           conda-forge     Cached
  + lzo                         2.10  hd590300_1001        conda-forge     Cached
  + minizip                    4.0.7  h401b404_0           conda-forge     Cached
  + ncurses                      6.5  he02047a_1           conda-forge     Cached
  + numpy                      2.0.2  py39h9cb892a_1       conda-forge        8MB
  + openssl                    3.4.0  hb9d3cd8_0           conda-forge     Cached
  + pcre2                      10.44  hba22ea6_2           conda-forge     Cached
  + pip                       24.3.1  pyh8b19718_0         conda-forge     Cached
  + proj                       9.5.1  h0054346_0           conda-forge     Cached
  + pyparsing                  3.2.0  pyhd8ed1ab_1         conda-forge     Cached
  + python                    3.9.20  h13acc7a_1_cpython   conda-forge       24MB
  + python_abi                   3.9  5_cp39               conda-forge        6kB
  + rasterio                   1.4.0  py39h44680f3_0       conda-forge        8MB
  + rav1e                      0.6.6  he8a937b_2           conda-forge     Cached
  + readline                     8.2  h8228510_1           conda-forge     Cached
  + setuptools                75.6.0  pyhff2d567_1         conda-forge     Cached
  + snappy                     1.2.1  ha2e4443_0           conda-forge     Cached
  + snuggs                     1.4.7  pyhd8ed1ab_1         conda-forge     Cached
  + sqlite                    3.47.0  h9eae976_1           conda-forge     Cached
  + svt-av1                    2.3.0  h5888daf_0           conda-forge     Cached
  + tk                        8.6.13  noxft_h4845f30_101   conda-forge     Cached
  + tzdata                     2024b  hc8b5060_0           conda-forge     Cached
  + uriparser                  0.9.8  hac33072_0           conda-forge     Cached
  + wheel                     0.45.1  pyhd8ed1ab_1         conda-forge     Cached
  + x265                         3.5  h924138e_3           conda-forge     Cached
  + xerces-c                   3.2.5  h988505b_2           conda-forge     Cached
  + xz                         5.2.6  h166bdaf_0           conda-forge     Cached
  + zipp                      3.21.0  pyhd8ed1ab_1         conda-forge     Cached
  + zlib                       1.3.1  hb9d3cd8_2           conda-forge     Cached
  + zstd                       1.5.6  ha6fb4c9_0           conda-forge     Cached
```

```
> from rasterio._io import Statistics
ImportError: libgdal.so.35: cannot open shared object file: No such file or directory
```

Well, as I debugged this locally, I am also getting

```
>>> import rasterio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/dev/lib/python3.9/site-packages/rasterio/__init__.py", line 25, in <module>
    from rasterio._io import Statistics
ImportError: /lib64/libldap.so.2: undefined symbol: EVP_md2, version OPENSSL_3.0.0
```

Happy Monday after a Holiday.  Am boggling this all now....

**Comment by akrherz** [comment]
Well, [build==0](https://conda-metadata-app.streamlit.app/?q=conda-forge%2Flinux-64%2Frasterio-1.4.0-py312heb92005_0.conda) of 1.4.0 has bad metadata with just a dependency on `gdal`.  build==1 seems to properly set gdal.  Build logs expired, sigh.  I think I am the one that fouled this up, so will just submit a request to mark those as broken....

**Comment by akrherz** [comment]
My admin request was merged to mark build=0 as broken, so will try this again once metadata gets updated.

With regards to my other error above with Opensssl.  I think this is due to the library link finding my local gdal.so.35 from pgrpms

> libgdal.so.35 => /usr/gdal39/lib/libgdal.so.35 (0x00007f9a58800000)

Which then links to a local openssl.  Will verify all is well in a few hours here...

**Comment by akrherz** [comment]
On linux-64 at least,

- [x] `mamba create -n dev python=3.9 rasterio=1.4.0 gdal=3.10` properly fails with unresolved dependencies.
- [ ] `mamba create -n dev python=3.9 rasterio gdal=3.10` fails though and now see there appears to be missing artifacts on the CDN, lolz.  Digging into that now.

**Comment by akrherz** [comment]
We are missing 3 builds for rasterio 1.4.2 build 1

- [ ] linux-64 python3.9
- [ ] linux-ppc64le python3.9
- [ ] linux-ppc64le python3.11

I can't seem to restart just those jobs, rerunning them all.  👀 CI
