### ISSUE TITLE
Issue with importing rasterio in clean environment

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/rasterio-feedstock#43]
In a clean Python 3.6 environment, I did:

```
$ conda install -c conda-forge rasterio ipython nomkl
```

but this leads to the following issue:

```
In [1]: import rasterio
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-350e27267e59> in <module>()
----> 1 import rasterio

~/miniconda3/envs/test-rasterio/lib/python3.6/site-packages/rasterio/__init__.py in <module>()
     13 import warnings
     14 
---> 15 from rasterio._base import (
     16     eval_window, window_shape, window_index, gdal_version)
     17 from rasterio.dtypes import (

ImportError: dlopen(/Users/tom/miniconda3/envs/test-rasterio/lib/python3.6/site-packages/rasterio/_base.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libnetcdf.11.dylib
  Referenced from: /Users/tom/miniconda3/envs/test-rasterio/lib/libgdal.20.dylib
  Reason: Incompatible library version: libgdal.20.dylib requires version 12.0.0 or later, but libnetcdf.11.dylib provides version 11.0.0
```

Just for the record:

```
$ conda list
# packages in environment at /Users/tom/miniconda3/envs/test-rasterio:
#
affine                    2.1.0                      py_1    conda-forge
appnope                   0.1.0                    py36_0    conda-forge
attrs                     17.2.0                   py36_0    conda-forge
boto3                     1.4.7                    py36_0    conda-forge
botocore                  1.5.92                   py36_0    conda-forge
ca-certificates           2017.08.26           ha1e5d58_0  
certifi                   2017.7.27.1      py36hd973bb6_0  
click                     6.7                      py36_0    conda-forge
click-plugins             1.0.3                    py36_0    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
curl                      7.54.1                        0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
geos                      3.5.1                         1    conda-forge
geotiff                   1.4.1                         0  
hdf4                      4.2.12                        0    conda-forge
hdf5                      1.8.17                       11    conda-forge
hypothesis                3.23.0                   py36_0    conda-forge
icu                       58.1                          1    conda-forge
ipython                   6.2.1                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jmespath                  0.9.3                    py36_0    conda-forge
jpeg                      9b                            1    conda-forge
kealib                    1.4.6                         3    conda-forge
krb5                      1.14.2                        0    conda-forge
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                hd939716_3  
libgdal                   2.1.0                         0  
libgfortran               3.0.0                         0    conda-forge
libnetcdf                 4.4.1                         0    conda-forge
libssh2                   1.8.0                         1    conda-forge
libtiff                   4.0.6                         7    conda-forge
ncurses                   6.0                  ha932d30_1  
nomkl                     1.0                           0  
numpy                     1.13.1             py36_nomkl_0  [nomkl]
openssl                   1.0.2l               h57f3a61_2  
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       9.0.1            py36hbd95645_3  
proj4                     4.9.2                         0  
prompt_toolkit            1.0.15                   py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pympler                   0.5                      py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
python                    3.6.3                h6804ab2_0  
python-dateutil           2.6.1                    py36_0    conda-forge
rasterio                  0.36.0                   py36_0    conda-forge
readline                  7.0                  h81b24a6_3  
s3transfer                0.1.11                   py36_0    conda-forge
setuptools                36.5.0           py36h2134326_0  
simplegeneric             0.8.1                    py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
snuggs                    1.4.1                    py36_0    conda-forge
sqlite                    3.20.1               h900c3b0_1  
tk                        8.6.7                hcdce994_1  
traitlets                 4.3.2                    py36_0    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
wheel                     0.29.0           py36h3597b6d_1  
xerces-c                  3.1.4                         3    conda-forge
xz                        5.2.3                ha24016e_1  
zlib                      1.2.11               h60db283_1  
zope                      1.0                      py36_0  
zope.interface            4.4.2                    py36_0  
```

**Comment by ocefpaf** [comment]
Are you using `Anaconda` or `miniconda`? `libgdal` is coming from `defaults` there. I get the right set of packages when creating a new env. Can you try that?

```shell
conda create --yes -n TEST python=3.6 rasterio ipython nomkl -c conda-forge
source activate TEST
python -c "import rasterio; print(rasterio.__version__)"  
0.36.0
```

```
> conda list
# packages in environment at /home/filipe/miniconda3/envs/TEST:
#
affine                    2.1.0                      py_1    conda-forge
attrs                     17.2.0                   py36_0    conda-forge
boost                     1.64.0                   py36_4    conda-forge
boost-cpp                 1.64.0                        1    conda-forge
boto3                     1.4.7                    py36_0    conda-forge
botocore                  1.5.92                   py36_0    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.7.27.1                   0    conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2017.7.27.1              py36_0    conda-forge
click                     6.7                      py36_0    conda-forge
click-plugins             1.0.3                    py36_0    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
curl                      7.54.1                        0    conda-forge
decorator                 4.1.2                    py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
expat                     2.1.0                         3    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
freexl                    1.0.2                         2    conda-forge
geos                      3.5.1                         1    conda-forge
gettext                   0.19.7                        1    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.51.4                        0    conda-forge
hdf4                      4.2.12                        0    conda-forge
hdf5                      1.8.18                        1    conda-forge
hypothesis                3.33.0                   py36_0    conda-forge
icu                       58.1                          1    conda-forge
ipython                   6.2.1                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
jedi                      0.10.2                   py36_0    conda-forge
jmespath                  0.9.3                    py36_0    conda-forge
jpeg                      9b                            1    conda-forge
json-c                    0.12.1                        0    conda-forge
kealib                    1.4.7                         3    conda-forge
krb5                      1.14.2                        0    conda-forge
libdap4                   3.18.3                        2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgdal                   2.1.4                         3    conda-forge
libgfortran               3.0.0                         1    defaults
libiconv                  1.14                          4    conda-forge
libkml                    1.3.0                         1    conda-forge
libnetcdf                 4.4.1.1                       6    conda-forge
libpng                    1.6.28                        1    conda-forge
libpq                     9.6.3                         0    conda-forge
libspatialite             4.3.0a                       15    conda-forge
libssh2                   1.8.0                         1    conda-forge
libtiff                   4.0.7                         0    conda-forge
libxml2                   2.9.5                         0    conda-forge
ncurses                   5.9                          10    conda-forge
nomkl                     1.0                           0    defaults
numpy                     1.13.1             py36_nomkl_0  [nomkl]  defaults
openblas                  0.2.19                        2    conda-forge
openjpeg                  2.1.2                         3    conda-forge
openssl                   1.0.2l                        0    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pixman                    0.34.0                        0    conda-forge
poppler                   0.52.0                        2    conda-forge
poppler-data              0.4.7                         0    conda-forge
proj4                     4.9.3                         4    conda-forge
prompt_toolkit            1.0.15                   py36_0    conda-forge
ptyprocess                0.5.2                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pympler                   0.5                      py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
python                    3.6.3                         0    conda-forge
python-dateutil           2.6.1                    py36_0    conda-forge
rasterio                  0.36.0                   py36_0    conda-forge
readline                  6.2                           0    conda-forge
s3transfer                0.1.11                   py36_0    conda-forge
setuptools                36.6.0                   py36_1    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
snuggs                    1.4.1                    py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        2    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
util-linux                2.21                          0    defaults
wcwidth                   0.1.7                    py36_0    conda-forge
wheel                     0.30.0                     py_1    conda-forge
xerces-c                  3.1.4                         3    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.8                         3    conda-forge
zope                      1.0                      py36_0    defaults
zope.interface            4.4.2                    py36_0    defaults
```

PS: `nomkl` does not ensure `numpy` with `openblas` from `conda-forge`.

**Comment by astrofrog** [comment]
@ocefpaf - I'm using miniconda. So the issue appears to be that:

```
$ conda create --yes -n TEST python=3.6 rasterio ipython nomkl -c conda-forge
$ source activate TEST
$ python -c "import rasterio; print(rasterio.__version__)"  
0.36.0
```

works, but:

```
$ conda create --yes -n TEST python=3.6
$ source activate TEST
$ conda install  rasterio ipython nomkl -c conda-forge
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tom/miniconda3/envs/test2/lib/python3.6/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import (
ImportError: dlopen(/Users/tom/miniconda3/envs/test2/lib/python3.6/site-packages/rasterio/_base.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libnetcdf.11.dylib
  Referenced from: /Users/tom/miniconda3/envs/test2/lib/libgdal.20.dylib
  Reason: Incompatible library version: libgdal.20.dylib requires version 12.0.0 or later, but libnetcdf.11.dylib provides version 11.0.0
```

doesn't. Is there a way to get around this with pinning? I'm trying to come up with a consistent set of instructions for users that doesn't require them having to create a new environment every time they want to update rasterio. I'm fine with solutions that require pinning specific versions of packages though.

**Comment by ocefpaf** [comment]
>  Is there a way to get around this with pinning?

You can probably force:

`conda create --yes -n TEST python=3.6 gdal=2.1.4 libgdal=2.1.4 rasterio`

**Comment by astrofrog** [comment]
@ocefpaf - thanks! And so in terms of longer term solution, is there a way we can make the rasterio package (or the dependency tree in general) more robust so it works with both install and when creating an environment?

**Comment by ocefpaf** [comment]
>  is there a way we can make the rasterio package (or the dependency tree in general) more robust so it works with both install and when creating an environment?

My hopes are with `conda-build 3`. Adding extra dependencies are not safe b/c conda can wiggle its way out by choosing lower build number, sometimes conda even breaks channel preference!
