### ISSUE TITLE
Import error with undefined symbol

### ISSUE THREAD

**Issue by mccarthyryanc** [conda-forge/rasterio-feedstock#48]
Getting the following error on Ubuntu 16.04:
```
$ python -c 'import rasterio'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/test/lib/python3.5/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import (
ImportError: /home/ubuntu/miniconda3/envs/test/lib/python3.5/site-packages/rasterio/../../.././libcurl.so.4: undefined symbol: libssh2_scp_recv2
```

Here is how I installed rasterio:
```
conda create -n test python=3.5 rasterio -c conda-forge
```

**Comment by mccarthyryanc** [comment]
looks like this is actually a gdal error:

```
$ python -c 'import gdal'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/miniconda3/envs/gdal-env/lib/python3.5/site-packages/gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/home/ubuntu/miniconda3/envs/gdal-env/lib/python3.5/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/home/ubuntu/miniconda3/envs/gdal-env/lib/python3.5/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/home/ubuntu/miniconda3/envs/gdal-env/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/ubuntu/miniconda3/envs/gdal-env/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /home/ubuntu/miniconda3/envs/gdal-env/lib/python3.5/site-packages/osgeo/../../.././libcurl.so.4: undefined symbol: libssh2_scp_recv2
```
I'll move the issue to the [gdal-feedstock](https://github.com/conda-forge/gdal-feedstock/issues/189).

**Comment by ocefpaf** [comment]
Just tried:

```
conda create -n test python=3.5 rasterio -c conda-forge
> python -c 'import rasterio;print(rasterio.__version__)'
0.36.0
```

and everything worked for me.

Can you send the results of `conda list` and `conda info -a` for that `test` env you created?
Also, check if your `.condarc` file and make sure `conda-forge` is on top of `defaults`. Here is mine:

```shell
> cat .condarc 
channels:
  - conda-forge
  - defaults
show_channel_urls: true
add_pip_as_python_dependency: true
```

Note that by passing `-c conda-forge` should be similar to having it on top, but you never know...

**Comment by mccarthyryanc** [comment]
Output from `conda list`:
```
# packages in environment at /home/mccarthyr/miniconda3/envs/test:
#
affine                    2.1.0                      py_1    conda-forge
attrs                     17.3.0                     py_0    conda-forge
boto3                     1.4.7                    py35_0    conda-forge
botocore                  1.5.92                   py35_0    conda-forge
ca-certificates           2017.11.5                     0    conda-forge
cairo                     1.14.6                        5    conda-forge
certifi                   2017.11.5                py35_0    conda-forge
click                     6.7                      py35_0    conda-forge
click-plugins             1.0.3                    py35_0    conda-forge
cligj                     0.4.0                    py35_0    conda-forge
curl                      7.55.1                        0    conda-forge
docutils                  0.14                     py35_0    conda-forge
expat                     2.1.0                         3    conda-forge
fontconfig                2.12.1                        5    conda-forge
freetype                  2.7                           2    conda-forge
freexl                    1.0.2                         2    conda-forge
gdal                      2.1.4                    py35_1    conda-forge
geos                      3.6.2                         1    conda-forge
geotiff                   1.4.2                         0    conda-forge
gettext                   0.19.7                        1    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.51.4                        0    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        1    conda-forge
icu                       58.2                          0    conda-forge
intel-openmp              2018.0.0             h15fc484_7  
jmespath                  0.9.3                    py35_0    conda-forge
jpeg                      9b                            2    conda-forge
json-c                    0.12.1                        0    conda-forge
kealib                    1.4.7                         4    conda-forge
krb5                      1.14.2                        0    conda-forge
libdap4                   3.18.3                        2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgdal                   2.1.4                         6    conda-forge
libgfortran               3.0.0                         1  
libiconv                  1.14                          4    conda-forge
libkml                    1.3.0                         3    conda-forge
libnetcdf                 4.4.1.1                      10    conda-forge
libpng                    1.6.28                        2    conda-forge
libpq                     9.6.3                         0    conda-forge
libspatialite             4.3.0a                       17    conda-forge
libssh2                   1.8.0                         2    conda-forge
libtiff                   4.0.7                         1    conda-forge
libxml2                   2.9.5                         1    conda-forge
mkl                       2018.0.0             hb491cac_4  
ncurses                   5.9                          10    conda-forge
numpy                     1.13.3           py35hd829ed6_0  
openjpeg                  2.1.2                         3    conda-forge
openssl                   1.0.2l                        0    conda-forge
pcre                      8.39                          0    conda-forge
pip                       9.0.1                    py35_0    conda-forge
pixman                    0.34.0                        0    conda-forge
poppler                   0.52.0                        3    conda-forge
poppler-data              0.4.7                         0    conda-forge
proj4                     4.9.3                         5    conda-forge
pyparsing                 2.2.0                    py35_0    conda-forge
python                    3.5.4                         1    conda-forge
python-dateutil           2.6.1                    py35_0    conda-forge
rasterio                  0.36.0                   py35_2    conda-forge
readline                  6.2                           0    conda-forge
s3transfer                0.1.11                   py35_0    conda-forge
setuptools                36.7.2                   py35_0    conda-forge
six                       1.11.0                   py35_1    conda-forge
snuggs                    1.4.1                    py35_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
tk                        8.5.19                        2    conda-forge
util-linux                2.21                          0  
wheel                     0.30.0                     py_1    conda-forge
xerces-c                  3.1.4                         3    conda-forge
xz                        5.2.3                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

Output of `conda info -a`:
```
Current conda install:

               platform : linux-64
          conda version : 4.3.30
       conda is private : False
      conda-env version : 4.3.30
    conda-build version : not installed
         python version : 3.6.3.final.0
       requests version : 2.18.4
       root environment : /home/mccarthyr/miniconda3  (writable)
    default environment : /home/mccarthyr/miniconda3/envs/test
       envs directories : /home/mccarthyr/miniconda3/envs
                          /home/mccarthyr/.conda/envs
          package cache : /home/mccarthyr/miniconda3/pkgs
                          /home/mccarthyr/.conda/pkgs
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.continuum.io/pkgs/main/linux-64
                          https://repo.continuum.io/pkgs/main/noarch
                          https://repo.continuum.io/pkgs/free/linux-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/linux-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/linux-64
                          https://repo.continuum.io/pkgs/pro/noarch
            config file : /home/mccarthyr/.condarc
             netrc file : None
           offline mode : False
             user-agent : conda/4.3.30 requests/2.18.4 CPython/3.6.3 Linux/4.4.0-101-generic debian/stretch/sid glibc/2.23    
                UID:GID : 1000:1000
# conda environments:
#
test                  *  /home/mccarthyr/miniconda3/envs/test
root                     /home/mccarthyr/miniconda3

sys.version: 3.6.3 |Anaconda, Inc.| (default, Oct 13 ...
sys.prefix: /home/mccarthyr/miniconda3
sys.executable: /home/mccarthyr/miniconda3/bin/python
conda location: /home/mccarthyr/miniconda3/lib/python3.6/site-packages/conda
conda-build: None
conda-env: /home/mccarthyr/miniconda3/bin/conda-env
user site dirs: ~/.local/lib/python3.5

CIO_TEST: <not set>
CONDA_DEFAULT_ENV: test
CONDA_ENVS_PATH: <not set>
CONDA_PATH_BACKUP: /home/mccarthyr/miniconda3/bin:/home/mccarthyr/src/gocode/bin:/home/mccarthyr/src/gocode/bin:/home/mccarthyr/anaconda3/bin:/home/mccarthyr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/oracle/12.1/client64//bin
CONDA_PREFIX: /home/mccarthyr/miniconda3/envs/test
CONDA_PS1_BACKUP: \[\e[38;5;202m\]$(byobu_prompt_status)\[\e[38;5;245m\]\u\[\e[00m\]@\[\e[38;5;172m\]\h\[\e[00m\]:\[\e[38;5;5m\]\w\[\e[00m\]$(byobu_prompt_symbol) 
CONDA_ROOT: /home/mccarthyr/miniconda3
DYLD_LIBRARY_PATH: <not set>
FTP_PROXY: <not set>
HTTPS_PROXY: <not set>
HTTP_PROXY: <not set>
LD_LIBRARY_PATH: /usr/lib/x86_64-linux-gnu
PATH: /home/mccarthyr/miniconda3/envs/test/bin:/home/mccarthyr/miniconda3/bin:/home/mccarthyr/src/gocode/bin:/home/mccarthyr/src/gocode/bin:/home/mccarthyr/anaconda3/bin:/home/mccarthyr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/oracle/12.1/client64//bin
PYTHONHOME: <not set>
PYTHONPATH: <not set>
REQUESTS_CA_BUNDLE: <not set>
SSL_CERT_FILE: <not set>

WARNING: could not import _license.show_info
# try:
# $ conda install -n root _license
```

Contents of `~/.condarc`:
```
channels:
  - conda-forge
  - defaults
```

**Comment by ocefpaf** [comment]
We have the same set of packages and everything works for me :confused:


See https://gist.github.com/ocefpaf/fca5573de27597082b0f99a7d879876c

That symbol is undefined though. You can check with:

```
nm ~/miniconda3/envs/test/lib/python3.5/site-packages/rasterio/../../.././libcurl.so.4 | grep libssh2_scp_recv2
```

I'll see what is causing that and hopefully fix curl. Thanks.

**Comment by mccarthyryanc** [comment]
Yep, undefined for me:
```
$ nm ~/miniconda3/envs/test/lib/python3.5/site-packages/rasterio/../../.././libcurl.so.4 | grep libssh2_scp_recv2
                 U libssh2_scp_recv2
```
It is really strange how it is undefined in both of our setups and only throwing the error in mine :man_shrugging:

**Comment by BenjaminWatts** [comment]
did you manage to fix this? -- I am getting same problem

**Comment by mccarthyryanc** [comment]
@BenjaminWatts, I think I have a workaround. I can't remember where I found this solution, but it was for something similar with another module/env. After you activate the environment, unset the library environment var:
```bash
unset LD_LIBRARY_PATH
```
Things behaved after that, but I'm not sure about the exact cause...

**Comment by BenjaminWatts** [comment]
Thanks -- v helpful will give a try

Kind Regards,

Ben

*Ben Watts* *(CGMA, MA Cantab) *- *+44 **20 8123 2809 / **+44 7730 611821*
*Block 3, The Forum, Grenville Street, St Helier, Jersey, JE2 4UF*

**Comment by jacobtomlinson** [comment]
I'm also struggling with this issue. The workaround suggested by @mccarthyryanc doesn't seem to help.

**Comment by sirgogo** [comment]
Same situation here.

**Comment by jacobtomlinson** [comment]
I found that upgrading gdal to 2.2.4 resolved the issue, however r-essentials don't let it go above 2.2.2. A workaround for now has been creating a new conda env without R.

**Comment by sirgogo** [comment]
Still an issue with 2.2.4

```
$ python
Python 3.5.5 |Anaconda, Inc.| (default, May 13 2018, 21:12:35) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ogr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.5/site-packages/ogr.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "/opt/conda/lib/python3.5/site-packages/osgeo/__init__.py", line 21, in <module>
    _gdal = swig_import_helper()
  File "/opt/conda/lib/python3.5/site-packages/osgeo/__init__.py", line 17, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "/opt/conda/lib/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/conda/lib/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /opt/conda/lib/python3.5/site-packages/osgeo/../../../libgdal.so.20: undefined symbol: _ZN11xercesc_3_211InputSource11setEncodingEPKDs
```

```
$ conda list
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
asn1crypto                0.24.0                   py35_0  
atomicwrites              1.1.5                    py35_0  
attrs                     18.1.0                   py35_0  
automat                   0.7.0                    py35_0  
backports                 1.0                py35_intel_6  [intel]  intel
beautifulsoup4            4.6.0            py35h442a8c9_1  
bleach                    1.5.0              py35_intel_0  [intel]  intel
bokeh                     0.13.0                   py35_0  
boost                     1.67.0           py35h3e44d54_0    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
bzip2                     1.0.6                  intel_14  [intel]  intel
ca-certificates           2018.4.16                     0    conda-forge
cachecontrol              0.12.5                   py35_0  
cairo                     1.14.12              h7636065_2  
certifi                   2018.4.16                py35_0    conda-forge
cffi                      1.9.1              py35_intel_1  [intel]  intel
chardet                   3.0.4            py35hb6e9ddf_1  
click                     6.7              py35h353a69f_0  
click-plugins             1.0.3                    py35_0  
cligj                     0.4.0                    py35_0  
conda                     4.5.8                    py35_0    conda-forge
conda-env                 2.6.0                h36134e3_1  
constantly                15.1.0                   py35_0  
cryptography              2.2.2            py35h14c3975_0  
cssselect                 1.0.3                    py35_0  
curl                      7.49.0                        1  
cycler                    0.10.0             py35_intel_5  [intel]  intel
cython                    0.25.2             py35_intel_4  [intel]  intel
dbus                      1.13.2               h714fa37_1  
decorator                 4.0.11             py35_intel_0  [intel]  intel
descartes                 1.1.0            py35h2f9c1c0_0  
entrypoints               0.2.2              py35_intel_2  [intel]  intel
expat                     2.2.5                hfc679d8_1    conda-forge
ffmpeg                    3.4.1                         0    conda-forge
fiona                     1.7.12                   py35_0    conda-forge
fontconfig                2.12.6               h49f89f6_0  
freetype                  2.8                     intel_0  [intel]  intel
freexl                    1.0.5                hf837533_1    conda-forge
future                    0.16.0                   py35_1  
gdal                      2.2.4                    py35_0    conda-forge
geojson                   2.4.0                     <pip>
geopandas                 0.3.0                      py_1    conda-forge
geos                      3.6.2                hfc679d8_2    conda-forge
geotiff                   1.4.2                hb54a4aa_2    conda-forge
get_terminal_size         1.0.0              py35_intel_5  [intel]  intel
giflib                    5.1.4                h470a237_0    conda-forge
glib                      2.56.1               h000015b_0  
graphite2                 1.3.11               hfc679d8_0    conda-forge
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb453b48_1  
h5py                      2.8.0            py35h470a237_0    conda-forge
harfbuzz                  1.7.6                h5f0a787_1  
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        2    conda-forge
html5lib                  0.999              py35_intel_0  [intel]  intel
hyperlink                 18.0.0                   py35_0  
icc_rt                    16.0.3                 intel_14  [intel]  intel
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                      py35_0  
imageio                   2.3.0                    py35_0  
incremental               17.5.0           py35head57c3_0  
intelpython               2018.0.3                      0    intel
ipp                       2017.0.3                intel_0  [intel]  intel
ipykernel                 4.5.0              py35_intel_9  [intel]  intel
ipyparallel               6.0.2              py35_intel_0  [intel]  intel
ipython                   5.3.0              py35_intel_0  [intel]  intel
ipython_genutils          0.2.0              py35_intel_0  [intel]  intel
jasper                    1.900.1                       4    conda-forge
jinja2                    2.9.5              py35_intel_3  [intel]  intel
jpeg                      9c                   h470a237_0    conda-forge
json-c                    0.13.1               h470a237_0    conda-forge
jsonschema                2.5.1              py35_intel_5  [intel]  intel
jupyter_client            5.0.0              py35_intel_0  [intel]  intel
jupyter_core              4.3.0              py35_intel_0  [intel]  intel
kealib                    1.4.7                         4    conda-forge
kiwisolver                1.0.1                    py35_1    conda-forge
krb5                      1.16.1               hbb41f41_0    conda-forge
lasagne                   0.1                      py35_0  
laspy                     1.5.1                     <pip>
libcurl                   7.60.0               h1ad7b7a_0  
libdap4                   3.19.1                        0    conda-forge
libedit                   3.1.20170329         h6b74fdf_2  
libffi                    3.2.1                   intel_8  [intel]  intel
libgcc-ng                 7.2.0                hdf63c60_3  
libgdal                   2.2.4                hc8d23f9_1  
libgfortran               3.0.0                         1  
libiconv                  1.15                 h63c8f33_5  
libkml                    1.3.0                hfce3912_7    conda-forge
libnetcdf                 4.4.1.1              h816af47_8  
libpng                    1.6.34                  intel_1  [intel]  intel
libpq                     10.3                 h1ad7b7a_0  
libsodium                 1.0.16                  intel_1  [intel]  intel
libspatialindex           1.8.5                h20b78c2_2  
libspatialite             4.3.0a              h72746d6_18  
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                   intel_2  [intel]  intel
libxcb                    1.13                 h470a237_1    conda-forge
libxml2                   2.9.8                h422b904_2    conda-forge
libxslt                   1.1.32               h88dbc4e_1    conda-forge
lockfile                  0.12.2                   py35_0  
lxml                      4.2.3            py35hc9114bc_0    conda-forge
markupsafe                0.23               py35_intel_6  [intel]  intel
mathjax                   2.2                      py35_0  
matplotlib                2.2.2            py35h0e671d2_1  
mistune                   0.7.4              py35_intel_0  [intel]  intel
mkl                       2017.0.3                intel_6  [intel]  intel
more-itertools            4.2.0                    py35_0  
mpmath                    0.19               py35_intel_5  [intel]  intel
msgpack-python            0.5.6            py35h6bb024c_0  
munch                     2.3.2                    py35_0  
natsort                   5.3.2                    py35_0  
nbconvert                 5.1.1              py35_intel_0  [intel]  intel
nbformat                  4.3.0              py35_intel_0  [intel]  intel
nbpresent                 3.0.2            py35h9c03491_1  
ncurses                   6.1                  hf484d3e_0  
networkx                  1.11               py35_intel_0  [intel]  intel
nose                      1.3.7             py35_intel_12  [intel]  intel
notebook                  5.0.0              py35_intel_0  [intel]  intel
numpy                     1.12.1             py35_intel_8  [intel]  intel
olefile                   0.44               py35_intel_0  [intel]  intel
opencv                    3.3.1            py35hb7523de_0  
openjpeg                  2.3.0                h0e734dc_3    conda-forge
openmp                    2017.0.4                intel_0    intel
openssl                   1.0.2o                        0    conda-forge
osmium                    2.14.1                    <pip>
overpass                  0.6.0                     <pip>
packaging                 17.1                     py35_0  
pandas                    0.20.1          np112py35_intel_1  [intel]  intel
pandocfilters             1.4.1              py35_intel_0  [intel]  intel
parsel                    1.4.0                    py35_0  
path.py                   10.1               py35_intel_0  [intel]  intel
pcre                      8.42                 h439df22_0  
pexpect                   4.2.1              py35_intel_0  [intel]  intel
pickleshare               0.7.4              py35_intel_1  [intel]  intel
pillow                    5.0.0                    py35_0    conda-forge
pip                       9.0.1              py35_intel_0  [intel]  intel
pixman                    0.34.0                  intel_0  [intel]  intel
plotly                    2.7.0                    py35_1  
pluggy                    0.6.0            py35hb428803_0  
Polygon3                  3.0.8                     <pip>
poppler                   0.65.0               ha54bb34_0  
poppler-data              0.4.9                         0    conda-forge
proj4                     4.9.3                         5    conda-forge
prompt_toolkit            1.0.14             py35_intel_0  [intel]  intel
protobuf                  3.2.0              py35_intel_0  [intel]  intel
psycopg2                  2.7.4            py35hb7f436b_0  
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.5.1              py35_intel_5  [intel]  intel
py                        1.5.3                    py35_0  
pyasn1                    0.4.3                    py35_0  
pyasn1-modules            0.2.2                    py35_0  
pycosat                   0.6.3            py35h6b6bb97_0  
pycparser                 2.17               py35_intel_0  [intel]  intel
pydaal                    2017.0.3.20170412 np112py35_intel_3  [intel]  intel
pydispatcher              2.0.5                    py35_0  
pygments                  2.2.0              py35_intel_0  [intel]  intel
pyopenssl                 18.0.0                   py35_0  
pyparsing                 2.1.4              py35_intel_5  [intel]  intel
pyproj                    1.9.5.1                  py35_0  
pyqt                      5.9.2            py35h751905a_0  
pyrtl                     0.8.6                     <pip>
pysal                     1.14.3                   py35_0  
pysocks                   1.6.8                    py35_0  
pytest                    3.6.2                    py35_0  
pytest-runner             4.2                      py35_0  
python                    3.5.5                hc3d631a_4  
python-dateutil           2.6.0              py35_intel_0  [intel]  intel
pytz                      2017.2             py35_intel_0  [intel]  intel
pywavelets                0.5.2           np112py35_intel_3  [intel]  intel
pyyaml                    3.12               py35_intel_1  [intel]  intel
pyzmq                     16.0.2             py35_intel_2  [intel]  intel
qt                        5.9.5                h7e424d6_0  
queuelib                  1.5.0                    py35_0  
readline                  7.0                  ha6073c6_4  
requests                  2.13.0             py35_intel_0  [intel]  intel
rtree                     0.8.3            py35h2f9c1c0_0  
ruamel_yaml               0.11.14            py35_intel_1  [intel]  intel
scikit-bio                0.5.1               np112py35_0  
scikit-image              0.13.0          np112py35_intel_1  [intel]  intel
scikit-learn              0.18.1             py35_intel_6  [intel]  intel
scikit-rf                 0.14.9                   py35_0  
scipy                     0.19.0          np112py35_intel_2  [intel]  intel
scrapy                    1.5.0                    py35_0  
service_identity          17.0.0                   py35_0  
setuptools                40.0.0                   py35_0    conda-forge
shapely                   1.5.16                   py35_0  
simplegeneric             0.8.1              py35_intel_5  [intel]  intel
sip                       4.19.8                   py35_0    conda-forge
six                       1.10.0             py35_intel_7  [intel]  intel
sqlalchemy                1.2.8            py35h14c3975_0  
sqlite                    3.23.1                  intel_0  [intel]  intel
sympy                     1.0                py35_intel_5  [intel]  intel
tbb                       2017.0.7           py35_intel_2  [intel]  intel
tcl                       8.6.4                  intel_19  [intel]  intel
terminado                 0.6                py35_intel_6  [intel]  intel
testpath                  0.3                py35_intel_0  [intel]  intel
theano                    1.1                py35_intel_2  [intel]  intel
tk                        8.6.7                         0    conda-forge
tornado                   4.4.2              py35_intel_0  [intel]  intel
traitlets                 4.3.2              py35_intel_0  [intel]  intel
Transplant                0.8.7                     <pip>
twisted                   17.5.0                   py35_0  
Tyf                       1.3.2                     <pip>
urllib3                   1.23                     py35_0  
util-linux                2.21                          0  
w3lib                     1.19.0                   py35_0  
wcwidth                   0.1.7              py35_intel_5  [intel]  intel
wheel                     0.29.0             py35_intel_5  [intel]  intel
x264                      20180712             h470a237_0    conda-forge
xerces-c                  3.2.1                h5d6a6da_1    conda-forge
xorg-libxau               1.0.8                h470a237_5    conda-forge
xorg-libxdmcp             1.1.2                h470a237_6    conda-forge
xz                        5.2.4                h14c3975_4  
yaml                      0.1.6                  intel_10  [intel]  intel
zeromq                    4.1.5                   intel_0  [intel]  intel
zlib                      1.2.11                  intel_3  [intel]  intel
zope                      1.0                      py35_0  
zope.interface            4.5.0            py35h14c3975_0
```

**Comment by snowman2** [comment]
@sirgogo, thanks for letting us know. It is actually not an issue for rasterio as the GDAL python bindings you are referring to are not a part of rasterio. We just recently made a change to reflect this and removed the GDAL python bindings dependency. You can install them with `conda install -c conda-forge gdal`.

**Comment by ocefpaf** [comment]
@sirgogo bare in mind that you have 3 channels there, defaults, conda-forge and intel. This is usually a recipe for disaster. Please read this issues and you'll find the recommended best practices and links to our docs.
