### ISSUE TITLE
libgdal and libiconv incompatibility

### ISSUE THREAD

**Issue by davidh-ssec** [conda-forge/rasterio-feedstock#53]
I have a OSX environment (haven't tested on others) that depends on gdal and rasterio. I've gotten in to the situation where it allows me to have `libiconv=1.14-4` and `rasterio=0.36.0` and `libgdal=2.1.4-8`. Running a simple test script `from rasterio import Affine` produces:

```
(sift) [davidh@thanatos sift]$ python test.py
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from rasterio import Affine
  File "/Users/davidh/anaconda/envs/sift/lib/python3.6/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import (
ImportError: dlopen(/Users/davidh/anaconda/envs/sift/lib/python3.6/site-packages/rasterio/_base.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libiconv.2.dylib
  Referenced from: /Users/davidh/anaconda/envs/sift/lib/libgdal.20.dylib
  Reason: Incompatible library version: libgdal.20.dylib requires version 9.0.0 or later, but libiconv.2.dylib provides version 8.0.0
```

If I update libiconv to 1.15-0 this error goes away. Also, I'm realizing now that my application may have just his the rasterio incompatibility first from import error. Doing `import gdal` also gets me a similar error to the above but from `osgeo/_gdal.cpython-36m-darwin.so`.

**Comment by ocefpaf** [comment]
Please send the `conda list` from that env. (You are installing in a separate env with conda-forge on top of defaults, right?)

Also, we are slowly updating the pinning scheme, so that may go away when we are done. Hopefully we'll finish by next week.

**Comment by davidh-ssec** [comment]
```
# packages in environment at /Users/davidh/anaconda/envs/sift:
#
affine                    2.0.0.post1              py36_0    conda-forge
appdirs                   1.4.3                      py_0    conda-forge
appnope                   0.1.0                    py36_0    conda-forge
astroid                   1.5.3                    py36_0    conda-forge
attrs                     17.2.0                   py36_0    conda-forge
basemap                   1.1.0                    py36_3    conda-forge
bleach                    2.0.0                    py36_0    conda-forge
boost                     1.64.0                   py36_4    conda-forge
boost-cpp                 1.64.0                        1    conda-forge
boto3                     1.4.4                    py36_0    conda-forge
botocore                  1.5.39                   py36_0    conda-forge
bumpversion               0.5.3                     <pip>
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2017.1.23                     1    conda-forge
cairo                     1.14.6                        4    conda-forge
certifi                   2017.4.17                py36_0    conda-forge
clangdev                  5.0.0                 default_0    conda-forge
click                     6.7                      py36_0    conda-forge
click-plugins             1.0.3                    py36_0    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
configobj                 5.0.6                    py36_0  
curl                      7.55.1                        0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cython                    0.26                     py36_0    conda-forge
decorator                 4.0.11                   py36_0    conda-forge
docutils                  0.13.1                   py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
expat                     2.1.0                         2    conda-forge
fontconfig                2.12.1                        4    conda-forge
freetype                  2.7                           1    conda-forge
freexl                    1.0.2                         1    conda-forge
future                    0.16.0                    <pip>
gdal                      2.1.4                    py36_1    conda-forge
geos                      3.6.2                         1    conda-forge
geotiff                   1.4.2                         0    conda-forge
gettext                   0.19.8.1                      0    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.51.4                        0    conda-forge
h5py                      2.7.1                    py36_2    conda-forge
hdf4                      4.2.12                        0    conda-forge
hdf5                      1.10.1                        1    conda-forge
html5lib                  0.999999999              py36_0    conda-forge
hypothesis                3.23.0                   py36_0    conda-forge
icu                       58.1                          1    conda-forge
imageio                   2.1.2                    py36_0    conda-forge
ipdb                      0.10.3                   py36_0    conda-forge
ipykernel                 4.6.1                    py36_0    conda-forge
ipython                   6.0.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                6.0.1                    py36_0    conda-forge
isort                     4.2.15                   py36_0    conda-forge
jedi                      0.10.0                   py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jmespath                  0.9.2                    py36_0    conda-forge
jpeg                      9b                            0    conda-forge
json-c                    0.12                          0    conda-forge
jsonschema                2.6.0                    py36_0    conda-forge
jupyter_client            5.0.1                    py36_0    conda-forge
jupyter_core              4.3.0                    py36_0    conda-forge
kealib                    1.4.7                         4    conda-forge
krb5                      1.14.2                        0    conda-forge
lazy-object-proxy         1.3.1                    py36_0    conda-forge
libcxx                    5.0.0                         0    conda-forge
libdap4                   3.18.3                        2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgdal                   2.1.4                         8    conda-forge
libgfortran               3.0.0                         0    conda-forge
libiconv                  1.14                          4    conda-forge
libkml                    1.3.0                         3    conda-forge
libnetcdf                 4.4.1.1                      10    conda-forge
libpng                    1.6.28                        0    conda-forge
libpq                     9.5.4                         4    conda-forge
libsodium                 1.0.15                        1    conda-forge
libspatialite             4.3.0a                       18    conda-forge
libssh2                   1.8.0                         2    conda-forge
libtiff                   4.0.6                         7    conda-forge
libxml2                   2.9.4                         4    conda-forge
llvmdev                   5.0.0                 default_0    conda-forge
llvmlite                  0.17.0                   py36_0  
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.0.0               np112py36_3    conda-forge
mccabe                    0.6.1                    py36_0    conda-forge
mistune                   0.8                      py36_0    conda-forge
mkl                       2017.0.1                      0  
nbconvert                 5.1.1                    py36_1    conda-forge
nbformat                  4.3.0                    py36_0    conda-forge
ncurses                   5.9                          10    conda-forge
netcdf4                   1.3.1                    py36_1    conda-forge
networkx                  1.11                     py36_0    conda-forge
notebook                  5.2.2                    py36_0    conda-forge
numba                     0.32.0              np112py36_0  
numpy                     1.12.1                   py36_0  
olefile                   0.44                     py36_0    conda-forge
openjpeg                  2.3.0                         1    conda-forge
openssl                   1.0.2k                        0    conda-forge
pandoc                    2.0.3                         0    conda-forge
pandocfilters             1.4.1                    py36_0    conda-forge
pcre                      8.39                          0    conda-forge
pexpect                   4.2.1                    py36_0    conda-forge
pickleshare               0.7.3                    py36_0    conda-forge
pillow                    4.1.0                    py36_0    conda-forge
pip                       9.0.1                    py36_0    conda-forge
pixman                    0.34.0                        0    conda-forge
poppler                   0.61.1                        2    conda-forge
poppler-data              0.4.7                         0    conda-forge
proj4                     4.9.3                         3    conda-forge
prompt_toolkit            1.0.14                   py36_0    conda-forge
ptyprocess                0.5.1                    py36_0    conda-forge
pygments                  2.2.0                    py36_0    conda-forge
pykdtree                  1.2.2                    py36_1    conda-forge
pylint                    1.7.1                    py36_0    conda-forge
pympler                   0.5                      py36_0    conda-forge
pyopengl                  3.1.0                    py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pyqt                      4.11.4                   py36_2    conda-forge
pyshp                     1.2.10                   py36_0    conda-forge
python                    3.6.3                         1    conda-forge
python-dateutil           2.6.0                    py36_0    conda-forge
python.app                1.2                      py36_4  
pytz                      2017.2                   py36_0    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
pyzmq                     16.0.2                   py36_2    conda-forge
qt                        4.8.7                         4  
rasterio                  0.36.0                   py36_2    conda-forge
readline                  6.2                           0    conda-forge
s3transfer                0.1.10                   py36_1    conda-forge
scipy                     0.19.0              np112py36_0  
setuptools                33.1.1                   py36_0    conda-forge
shapely                   1.6.3                    py36_0    conda-forge
simplegeneric             0.8.1                    py36_0    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.10.0                   py36_1    conda-forge
snuggs                    1.4.1                    py36_0    conda-forge
sqlalchemy                1.1.13                   py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
terminado                 0.8.1                    py36_0    conda-forge
testpath                  0.3.1                    py36_0    conda-forge
tifffile                  0.12.1                    <pip>
tk                        8.5.19                        1    conda-forge
tornado                   4.5.1                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
trollimage                1.0.2                     <pip>
trollsift                 0.2.0                     <pip>
vispy                     0.5.0                    py36_1    conda-forge
wcwidth                   0.1.7                    py36_0    conda-forge
webencodings              0.5                      py36_0    conda-forge
wheel                     0.29.0                   py36_0    conda-forge
widgetsnbextension        2.0.0                    py36_0    conda-forge
wrapt                     1.10.11                  py36_0    conda-forge
xerces-c                  3.2.0                         0    conda-forge
xz                        5.2.2                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zeromq                    4.2.1                         1    conda-forge
zlib                      1.2.11                        0    conda-forge
zope                      1.0                      py36_0  
zope.interface            4.4.2                    py36_0  
```

**Comment by raybellwaves** [comment]
I am seconding this issue.

On OS v10.13.2

`conda install -c conda-forge rasterio`

`>>> import rasterio`
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/Ray/anaconda/lib/python3.6/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import (`
`ImportError: dlopen(/Users/Ray/anaconda/lib/python3.6/site-packages/rasterio/_base.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libiconv.2.dylib`
  `Referenced from: /Users/Ray/anaconda/lib/libgdal.20.dylib`
  `Reason: Incompatible library version: libgdal.20.dylib requires version 9.0.0 or later, but libiconv.2.dylib provides version 8.0.0`

**Comment by rabernat** [comment]
I just hit this exact same error.

**Comment by ocefpaf** [comment]
@davidh-ssec can you check if you are still experiencing this with the latest packages?

**Comment by davidh-ssec** [comment]
@ocefpaf It seems I'm unable to recreate the environment that caused this issue. Seems like 0.36.0_3 is always requested so without trying really hard I don't think I can get the situation where libiconv 1.14-4 is not replaced by a newer version.

**Comment by ocefpaf** [comment]
Cool! Closing this then. Let me know if you hit this issue again.
