### ISSUE TITLE
ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by patrickcgray** [conda-forge/rasterio-feedstock#58]
In Ubuntu 16.04 I created a new Anaconda environment with this command:
`conda create --name GIS python=3.6 rasterio
`

And got this error, no luck in debugging on my end:

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/clifgray/anaconda3/envs/GIS/lib/python3.6/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import (
ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory
`

**Comment by patrickcgray** [comment]
Turns out that this happens when you don't pull from conda-forge. Specifying `conda install -c conda-forge rasterio` fixes this issue.
