### ISSUE TITLE
HDF5 link error in fresh environment

### ISSUE THREAD

**Issue by djhoese** [conda-forge/rasterio-feedstock#66]
I'm getting the following error message when trying to create a new environment with rasterio:

```bash
$ python -c "from rasterio import Affine"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/users/davidh/anaconda3/envs/sift_2/lib/python3.6/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import (
ImportError: libhdf5_cpp.so.102: cannot open shared object file: No such file or directory
```

This is on CentOS 7 and the create command is:

```bash
conda create -n sift_2 python=3.6 vispy gdal rasterio matplotlib "pyqt<5" pyqtgraph satpy
```

**Comment by djhoese** [comment]
Looks like this installs 0.36.0 build 2 when there is actually a build 3 available on anaconda.org.

**Comment by djhoese** [comment]
```bash
conda install "rasterio=0.36.0=py36_3"
```

<details>

```
Solving environment: done

## Package Plan ##

  environment location: /data/users/davidh/anaconda3/envs/sift_2

  added / updated specs: 
    - rasterio==0.36.0=py36_3


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libpq-9.6.6                |       h4e02ad2_0         101 KB
    xorg-renderproto-0.11.1    |       h470a237_2           8 KB  conda-forge
    boost-1.67.0               |   py36h3e44d54_0         316 KB  conda-forge
    xorg-libsm-1.2.2           |                2          31 KB  conda-forge
    libdap4-3.19.1             |                0        15.6 MB  conda-forge
    libgdal-2.2.2              |       h804cdde_1        16.1 MB
    pango-1.40.14              |       hd50be51_1         527 KB  conda-forge
    gdal-2.2.2                 |   py36hc209d97_1         767 KB
    boost-cpp-1.67.0           |       h3a22d5f_0        19.7 MB  conda-forge
    poppler-0.66.0             |       hb55ee21_1         8.5 MB  conda-forge
    qt-4.8.7                   |                4        32.7 MB
    xorg-xproto-7.0.31         |       h470a237_7          72 KB  conda-forge
    xorg-kbproto-1.0.7         |       h470a237_2          25 KB  conda-forge
    xorg-libice-1.0.9          |                2          80 KB  conda-forge
    xorg-libx11-1.6.5          |                0         1.6 MB  conda-forge
    libkml-1.3.0               |       hfce3912_7         608 KB  conda-forge
    xorg-libxrender-0.9.10     |                0          34 KB  conda-forge
    cairo-1.14.12              |       he56eebe_0         1.3 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        98.0 MB

The following NEW packages will be INSTALLED:

    boost:            1.67.0-py36h3e44d54_0 conda-forge
    boost-cpp:        1.67.0-h3a22d5f_0     conda-forge
    bzip2:            1.0.6-1               conda-forge
    libgdal:          2.2.2-h804cdde_1                 
    libkml:           1.3.0-hfce3912_7      conda-forge
    libuuid:          1.0.3-1               conda-forge
    libxcb:           1.13-h470a237_0       conda-forge
    poppler:          0.66.0-hb55ee21_1     conda-forge
    poppler-data:     0.4.9-0               conda-forge
    xorg-kbproto:     1.0.7-h470a237_2      conda-forge
    xorg-libice:      1.0.9-2               conda-forge
    xorg-libsm:       1.2.2-2               conda-forge
    xorg-libx11:      1.6.5-0               conda-forge
    xorg-libxau:      1.0.8-h470a237_4      conda-forge
    xorg-libxdmcp:    1.1.2-h470a237_4      conda-forge
    xorg-libxrender:  0.9.10-0              conda-forge
    xorg-renderproto: 0.11.1-h470a237_2     conda-forge
    xorg-xproto:      7.0.31-h470a237_7     conda-forge

The following packages will be REMOVED:

    matplotlib:       2.0.0-np112py36_2     conda-forge

The following packages will be UPDATED:

    cairo:            1.14.6-5              conda-forge --> 1.14.12-he56eebe_0   conda-forge
    expat:            2.1.0-3               conda-forge --> 2.2.5-hfc679d8_1     conda-forge
    fontconfig:       2.12.1-6              conda-forge --> 2.13.0-0             conda-forge
    freetype:         2.7-2                 conda-forge --> 2.8.1-0              conda-forge
    gdal:             2.1.3-py36_7          conda-forge --> 2.2.2-py36hc209d97_1            
    glib:             2.51.4-0              conda-forge --> 2.55.0-0             conda-forge
    harfbuzz:         1.4.3-0               conda-forge --> 1.7.6-0              conda-forge
    libdap4:          3.18.3-2              conda-forge --> 3.19.1-0             conda-forge
    libpng:           1.6.28-2              conda-forge --> 1.6.34-ha92aebf_1    conda-forge
    libpq:            9.6.3-0               conda-forge --> 9.6.6-h4e02ad2_0                
    libspatialite:    4.3.0a-18             conda-forge --> 4.3.0a-19            conda-forge
    libtiff:          4.0.7-1               conda-forge --> 4.0.9-he6b73bb_1     conda-forge
    openjpeg:         2.1.2-3               conda-forge --> 2.3.0-h0e734dc_3     conda-forge
    pango:            1.40.4-0              conda-forge --> 1.40.14-hd50be51_1   conda-forge
    pillow:           4.3.0-py36_1          conda-forge --> 5.2.0-py36_0         conda-forge
    python:           3.6.3-1               conda-forge --> 3.6.5-1              conda-forge
    rasterio:         0.36.0-py36_2         conda-forge --> 0.36.0-py36_3        conda-forge
    readline:         6.2-0                 conda-forge --> 7.0-0                conda-forge
    sqlite:           3.13.0-1              conda-forge --> 3.20.1-2             conda-forge
    tk:               8.5.19-2              conda-forge --> 8.6.7-0              conda-forge

The following packages will be DOWNGRADED:

    json-c:           0.13.1-h470a237_0     conda-forge --> 0.12.1-0             conda-forge
    qt:               4.8.7-7               conda-forge --> 4.8.7-4                         

Proceed ([y]/n)? 


Downloading and Extracting Packages
libpq-9.6.6          |  101 KB | ############################################################################################################################################################### | 100% 
xorg-renderproto-0.1 |    8 KB | ############################################################################################################################################################### | 100% 
boost-1.67.0         |  316 KB | ############################################################################################################################################################### | 100% 
xorg-libsm-1.2.2     |   31 KB | ############################################################################################################################################################### | 100% 
libdap4-3.19.1       | 15.6 MB | ############################################################################################################################################################### | 100% 
libgdal-2.2.2        | 16.1 MB | ############################################################################################################################################################### | 100% 
pango-1.40.14        |  527 KB | ############################################################################################################################################################### | 100% 
gdal-2.2.2           |  767 KB | ############################################################################################################################################################### | 100% 
boost-cpp-1.67.0     | 19.7 MB | ############################################################################################################################################################### | 100% 
poppler-0.66.0       |  8.5 MB | ############################################################################################################################################################### | 100% 
qt-4.8.7             | 32.7 MB | ############################################################################################################################################################### | 100% 
xorg-xproto-7.0.31   |   72 KB | ############################################################################################################################################################### | 100% 
xorg-kbproto-1.0.7   |   25 KB | ############################################################################################################################################################### | 100% 
xorg-libice-1.0.9    |   80 KB | ############################################################################################################################################################### | 100% 
xorg-libx11-1.6.5    |  1.6 MB | ############################################################################################################################################################### | 100% 
libkml-1.3.0         |  608 KB | ############################################################################################################################################################### | 100% 
xorg-libxrender-0.9. |   34 KB | ############################################################################################################################################################### | 100% 
cairo-1.14.12        |  1.3 MB | ############################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

```

</details>

Results in:

```
$ python -c "from rasterio import Affine"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/users/davidh/anaconda3/envs/sift_2/lib/python3.6/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import (
ImportError: libpoppler.so.71: cannot open shared object file: No such file or directory
```

**Comment by djhoese** [comment]
Ok so then `conda update gdal` got me:

```
Solving environment: done

## Package Plan ##

  environment location: /data/users/davidh/anaconda3/envs/sift_2

  added / updated specs: 
    - gdal


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    h5py-2.8.0                 |   py36hb794570_1         3.7 MB  conda-forge
    netcdf4-1.4.0              |   py36hd4b6044_1         536 KB
    hdf5-1.10.2                |                0         4.8 MB  conda-forge
    libgdal-2.2.4              |       ha6e4b24_6        15.7 MB  conda-forge
    libnetcdf-4.6.1            |       h5e45101_3         1.3 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        26.1 MB

The following NEW packages will be INSTALLED:

    cftime:    1.0.0-py36_0         conda-forge
    geotiff:   1.4.2-hb54a4aa_2     conda-forge

The following packages will be UPDATED:

    gdal:      2.2.2-py36hc209d97_1             --> 2.2.4-py36_0         conda-forge
    h5py:      2.8.0-py36h470a237_0 conda-forge --> 2.8.0-py36hb794570_1 conda-forge
    hdf5:      1.10.1-2             conda-forge --> 1.10.2-0             conda-forge
    libgdal:   2.2.2-h804cdde_1                 --> 2.2.4-ha6e4b24_6     conda-forge
    libnetcdf: 4.4.1.1-10           conda-forge --> 4.6.1-h5e45101_3     conda-forge
    netcdf4:   1.3.1-py36_1         conda-forge --> 1.4.0-py36hd4b6044_1            

The following packages will be DOWNGRADED:

    poppler:   0.66.0-hb55ee21_1    conda-forge --> 0.61.1-3             conda-forge

Proceed ([y]/n)? 


Downloading and Extracting Packages
h5py-2.8.0           |  3.7 MB | ############################################################################################################################################################### | 100% 
netcdf4-1.4.0        |  536 KB | ############################################################################################################################################################### | 100% 
hdf5-1.10.2          |  4.8 MB | ############################################################################################################################################################### | 100% 
libgdal-2.2.4        | 15.7 MB | ############################################################################################################################################################### | 100% 
libnetcdf-4.6.1      |  1.3 MB | ############################################################################################################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

And a working environment (WTF):

```
$ python -c "from rasterio import Affine"
```

**Comment by djhoese** [comment]
Looks like one of the main differences between working and not working is `hdf5=1.10.2`, but conda does not automatically allow that version of hdf5 to be installed with the other dependencies:

```
failed to get install actions, retrying.  exception was: The following specifications were found to be in conflict:
  - hdf5[version='>=1.10.2']
  - matplotlib
  - numpy[version='>=1.12']
  - pyqt[version='<5']
  - rasterio
Use "conda info <package>" to see the dependencies for each package.
WARNING:conda_build.environ:failed to get install actions, retrying.  exception was: The following specifications were found to be in conflict:
  - hdf5[version='>=1.10.2']
  - matplotlib
  - numpy[version='>=1.12']
  - pyqt[version='<5']
  - rasterio
Use "conda info <package>" to see the dependencies for each package.
Solving environment: ...working... failed
```

**Comment by snowman2** [comment]
@ocefpaf, I have noticed this as well. Is this a libgdal issue?

It works when I pin:
```
hdf5=1.10.2
kealib=1.4.9
```
Thoughts?

**Comment by snowman2** [comment]
@djhoese is works with:
`conda create -n sift_2 python=3.6 vispy gdal rasterio matplotlib "pyqt<5" pyqtgraph satpy kealib=1.4.7`

**Comment by ocefpaf** [comment]
My guess is that the latest PR to `kealib` fixed this.
Can you test it again and let me know?

**Comment by djhoese** [comment]
@ocefpaf This seems to work from the `create` command when creating an environment. However, I can't seem to get it to work for an existing environment. If you take an environment that doesn't have rasterio installed (I had just uninstalled it to prove this is broken):

```bash
(sift_2) [davidh@bumi ~]$ conda install rasterio
Solving environment: done

## Package Plan ##

  environment location: /data/users/davidh/anaconda3/envs/sift_2

  added / updated specs: 
    - rasterio


The following NEW packages will be INSTALLED:

    rasterio: 0.36.0-py36_2 conda-forge

Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(sift_2) [davidh@bumi ~]$ python -c "from rasterio import Affine"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/users/davidh/anaconda3/envs/sift_2/lib/python3.6/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import (
ImportError: libgdal.so.20: cannot open shared object file: No such file or directory
```

If I then install libgdal (already have "gdal" installed):

```bash
(sift_2) [davidh@bumi ~]$ conda install libgdal
Solving environment: done

## Package Plan ##

  environment location: /data/users/davidh/anaconda3/envs/sift_2

  added / updated specs: 
    - libgdal


The following NEW packages will be INSTALLED:

    libgdal: 2.0.0-1

Proceed ([y]/n)? 

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(sift_2) [davidh@bumi ~]$ python -c "from rasterio import Affine"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/users/davidh/anaconda3/envs/sift_2/lib/python3.6/site-packages/rasterio/__init__.py", line 15, in <module>
    from rasterio._base import (
ImportError: libgeos-3.4.2.so: cannot open shared object file: No such file or directory
```

So it seems like rasterio either has a `libgdal` or `libgeos` ("geos") dependency missing, right?

**Comment by djhoese** [comment]
Cancel that, I got my existing environment to work by uninstalling "gdal" and "rasterio". Then when I reinstalled "rasterio" it forced the "gdal" requirement of 2.1.3 and my import test seems to pass.
