### ISSUE TITLE
Install rasterio 1.0, matplotlib, and pyqt4

### ISSUE THREAD

**Issue by djhoese** [conda-forge/rasterio-feedstock#71]
Issue:

I can't seem to find a way to install rasterio 1.0 with PyQt4 and matplotlib. Is there any way this can be done currently? I don't *need* rasterio 1.0 right now but was hoping that it would build better than 0.36.0. I'm bundling up my application using pyinstaller for the final version that uses PyQt4 (hopefully) so in the future this shouldn't be as much of a pain.

```
$ conda install "qt<5" "rasterio>=1"
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - matplotlib
  - qt[version='<5']
  - rasterio[version='>=1']

```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list 
# packages in environment at /data/users/davidh/anaconda3/envs/sift:
#
# Name                    Version                   Build  Channel
affine                    2.2.1                      py_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                0.24.0                   py36_0    conda-forge
attrs                     18.1.0                     py_1    conda-forge
blas                      1.0                         mkl  
bokeh                     0.12.16                  py36_0    conda-forge
boost                     1.66.0                   py36_1    conda-forge
boost-cpp                 1.66.0                        1    conda-forge
boto3                     1.7.50                     py_0    conda-forge
botocore                  1.10.50                    py_0    conda-forge
bottleneck                1.2.1            py36h7eb728f_1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cairo                     1.14.6                        5    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
cftime                    1.0.0                    py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
click                     6.7                        py_1    conda-forge
click-plugins             1.0.3                    py36_0    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
cloudpickle               0.5.3                      py_0    conda-forge
configobj                 5.0.6                    py36_0  
coverage                  4.5.1                    py36_0    conda-forge
cryptography              2.2.1            py36hdffb7b8_1    conda-forge
curl                      7.60.0                        0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cython                    0.28.3           py36hfc679d8_0    conda-forge
cytoolz                   0.9.0.1                  py36_0    conda-forge
dask                      0.18.1                     py_0    conda-forge
dask-core                 0.18.1                     py_0    conda-forge
dbus                      1.11.0                        0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
distributed               1.22.0                   py36_0    conda-forge
docutils                  0.14                     py36_0    conda-forge
ecmwf_grib                1.23.1                        1    conda-forge
expat                     2.1.0                         3    conda-forge
fontconfig                2.12.1                        6    conda-forge
freetype                  2.7                           2    conda-forge
freexl                    1.0.5                hf837533_1    conda-forge
future                    0.16.0                    <pip>
gdal                      2.1.3                    py36_7    conda-forge
geos                      3.6.2                hfc679d8_2    conda-forge
geotiff                   1.4.2                hb54a4aa_2    conda-forge
gettext                   0.19.8.1                      0    conda-forge
giflib                    5.1.4                h470a237_0    conda-forge
glib                      2.51.4                        0    conda-forge
goesr                     0.4.2                         0    http://larch.ssec.wisc.edu/channels/sift
graphite2                 1.3.11               hfc679d8_0    conda-forge
gst-plugins-base          1.8.0                         0    conda-forge
gstreamer                 1.8.0                         1    conda-forge
h5netcdf                  0.6.1                      py_0    conda-forge
h5py                      2.8.0            py36h470a237_0    conda-forge
harfbuzz                  1.4.3                         0    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        2    conda-forge
heapdict                  1.0.0                    py36_0    conda-forge
hypothesis                3.61.0           py36h24bf2e0_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                      py36_0    conda-forge
imageio                   2.3.0                    py36_0    conda-forge
intel-openmp              2018.0.3                      0  
jasper                    1.900.1                       4    conda-forge
jinja2                    2.10                     py36_0    conda-forge
jmespath                  0.9.3                    py36_0    conda-forge
jpeg                      9c                   h470a237_0    conda-forge
json-c                    0.12.1                        0    conda-forge
kealib                    1.4.7                         4    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
krb5                      1.14.6                        0    conda-forge
libboost                  1.65.1               habcd387_4  
libdap4                   3.18.3                        2    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    7.2.0                h69d50b8_2  
libgcc-ng                 7.2.0                hdf63c60_3  
libgfortran               3.0.0                         1  
libgfortran-ng            7.2.0                hdf63c60_3  
libiconv                  1.15                 h470a237_1    conda-forge
libkml                    1.3.0                h8777076_2  
libnetcdf                 4.4.1.1                      10    conda-forge
libopenblas               0.2.20               h9ac9557_7  
libpng                    1.6.28                        2    conda-forge
libpq                     9.6.3                         0    conda-forge
libspatialite             4.3.0a                       18    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3  
libtiff                   4.0.9                he6b73bb_1    conda-forge
libxcb                    1.13                 h470a237_0    conda-forge
libxml2                   2.9.8                h422b904_1    conda-forge
llvmlite                  0.23.0                   py36_1    conda-forge
locket                    0.2.0                    py36_1    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.0.0               np112py36_2    conda-forge
mkl                       2018.0.3                      1  
mkl_fft                   1.0.2                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
msgpack-python            0.5.6            py36h2d50403_2    conda-forge
ncurses                   5.9                          10    conda-forge
netcdf4                   1.3.1                    py36_1    conda-forge
networkx                  2.1                      py36_0    conda-forge
numba                     0.38.1                   py36_0    conda-forge
numpy                     1.12.1           py36he24570b_1  
numpy-base                1.14.3           py36h0ea5e3f_1  
olefile                   0.45.1                   py36_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openjpeg                  2.1.2                         3    conda-forge
openssl                   1.0.2o                        0    conda-forge
packaging                 17.1                       py_0    conda-forge
pandas                    0.23.1                   py36_0    conda-forge
pango                     1.40.4                        0    conda-forge
partd                     0.3.8                    py36_0    conda-forge
pcre                      8.41                          1    conda-forge
pillow                    4.2.1                    py36_0    conda-forge
pip                       9.0.3                    py36_0    conda-forge
pixman                    0.34.0                        2    conda-forge
poppler                   0.52.0                        2    conda-forge
poppler-data              0.4.9                         0    conda-forge
proj4                     4.9.3                         5    conda-forge
psutil                    5.4.6                    py36_0    conda-forge
pycparser                 2.18                     py36_0    conda-forge
pygrib                    2.0.2                    py36_2    conda-forge
PyInstaller               3.4.dev0+g59387c9           <pip>
pykdtree                  1.3.1                    py36_0    conda-forge
pympler                   0.5                      py36_0    conda-forge
pyopengl                  3.1.1a1                  py36_0    conda-forge
pyopenssl                 18.0.0                   py36_0    conda-forge
pyparsing                 2.2.0                    py36_0    conda-forge
pyproj                    1.9.5.1                  py36_0    conda-forge
pyqt                      4.11.4                   py36_3    conda-forge
pyqtgraph                 0.10.0                     py_3    conda-forge
pyresample                1.10.0                   py36_0    conda-forge
pyshp                     1.2.12                     py_0    conda-forge
pysocks                   1.6.8                    py36_1    conda-forge
pyspectral                0.7.2                      py_0    conda-forge
python                    3.6.3                         1    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
python-geotiepoints       1.1.5            py36h24bf2e0_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pywavelets                0.5.2                    py36_1    conda-forge
pyyaml                    3.12                     py36_1    conda-forge
qt                        4.8.7                         7    conda-forge
quamash                   0.6.0                      py_0    http://larch.ssec.wisc.edu/channels/sift
rasterio                  0.36.0                   py36_2    conda-forge
readline                  6.2                           0    conda-forge
requests                  2.19.1                   py36_0    conda-forge
s3transfer                0.1.13                   py36_0    conda-forge
satpy                     0.9.0              pyh326bf55_0    conda-forge
scikit-image              0.13.1                   py36_0    conda-forge
scipy                     1.1.0            py36hfc37229_0  
setuptools                39.2.0                   py36_0    conda-forge
shapely                   1.6.4            py36h164cb2d_1    conda-forge
sip                       4.18                     py36_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
snuggs                    1.4.1                    py36_0    conda-forge
sortedcontainers          2.0.4                    py36_0    conda-forge
sqlalchemy                1.2.9                    py36_0    conda-forge
sqlite                    3.13.0                        1    conda-forge
tblib                     1.3.2                    py36_0    conda-forge
tk                        8.5.19                        2    conda-forge
toolz                     0.9.0                      py_0    conda-forge
tornado                   5.0.2                    py36_0    conda-forge
tqdm                      4.23.4                     py_0    conda-forge
trollimage                1.5.3                    py36_0    conda-forge
trollsift                 0.2.1                      py_0    conda-forge
urllib3                   1.23                     py36_0    conda-forge
util-linux                2.21                          0  
vispy                     0.6.0.dev0               py36_4    http://larch.ssec.wisc.edu/channels/sift
wheel                     0.31.0                   py36_0    conda-forge
xarray                    0.10.7                   py36_0    conda-forge
xerces-c                  3.2.0                         0    conda-forge
xorg-libxau               1.0.8                h470a237_4    conda-forge
xorg-libxdmcp             1.1.2                h470a237_4    conda-forge
xz                        5.2.3                         0    conda-forge
yaml                      0.1.7                         0    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
zope                      1.0                      py36_0  
zope.interface            4.5.0            py36h470a237_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : sift
    active env location : /data/users/davidh/anaconda3/envs/sift
            shell level : 1
       user config file : /home/davidh/.condarc
 populated config files : /home/davidh/.condarc
          conda version : 4.5.6
    conda-build version : 3.10.9
         python version : 3.6.1.final.0
       base environment : /data/users/davidh/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /data/users/davidh/anaconda3/pkgs
                          /home/davidh/.conda/pkgs
       envs directories : /data/users/davidh/anaconda3/envs
                          /home/davidh/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.6 requests/2.14.2 CPython/3.6.1 Linux/3.10.0-327.3.1.el7.x86_64 centos/7 glibc/2.17
                UID:GID : 53807:700
             netrc file : None
           offline mode : False

```
</details>

**Comment by ocefpaf** [comment]
Unfortunately most of our stack is pinned to `qt 5`, like matplotlib. We should be able to have mpl working with both version of `qt`, I'll see what I can do.

**Comment by djhoese** [comment]
The weird thing I can't imagine what is requiring a new-ish version of matplotlub since I'm 99% sure there are still older versions that allow qt4.

**Comment by ocefpaf** [comment]
There are but we don't keep up with the pinning there and you are probably not able to find a version that has working dependencies.

**Comment by djhoese** [comment]
This seems to be do-able as far as *only* requiring rasterio, matplotlib, and pyqt4. The current impossible environment is described here https://github.com/conda-forge/matplotlib-feedstock/issues/164.

**Comment by ocefpaf** [comment]
Good to know. The problem there is how conda tries to optimize its version, b/c gdal is listed in the impossible env, conda tries to get the latest gdal but cannot solve due to missing dependencies (packages built with the same pinnings as gdal).

If you omit gdal conda will be more flexible and get an older gdal that has "satisfiable" dependencies.

**Comment by djhoese** [comment]
If my users all specify my custom HTTP conda channel (`-c http://...` and already have conda-forge in global config) and I copy a "satisfiable" conda-forge version of gdal there, should that allow gdal to be installed? I guess not.

I'm trying a few things, currently some package is requiring a downgrade to python 3.5 so this is fun.

**Comment by djhoese** [comment]
FYI with rasterio 1.0+ I was unable to take an existing environment and get it to a point where I could import rasterio's Affine:

```bash
$ python -c "from rasterio import Affine"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/data/users/davidh/anaconda3/envs/sift/lib/python3.6/site-packages/rasterio/__init__.py", line 23, in <module>
    from rasterio._base import gdal_version
ImportError: /data/users/davidh/anaconda3/envs/sift/lib/python3.6/site-packages/rasterio/../../../libgdal.so.20: undefined symbol: _ZN9kmlengine4Href5ParseERKSs
```

I tried uninstalling all of the possibly relevant packages or so I thought (gdal, libgdal, rasterio, kealib, krb5, matplotlib, pyqt, qt, etc) and then reinstalling and I kept getting the same error. I deleted the environment and recreated it and installed all the same packages and it works. WTF. I no longer have the patience to debug this specific issue.

**Comment by ocefpaf** [comment]
> I deleted the environment and recreated it and installed all the same packages and it works,

That is the recommended workflow for conda. Updating packages, or installing new packages into an existing env, has been a nightmare due to how the packages are solved.

**Comment by djhoese** [comment]
> That is the recommended workflow for conda. Updating packages, or installing new packages into an existing env, has been a nightmare due to how the packages are solved.

I am not a new conda user and have experience writing a lot of software so I understand, but at the same time how can that be the "recommended" workflow? How can conda consider itself a package manager if it can't resolve package dependencies and manage an environment? What if this sub-environment that I was using was my base environment? I'm supposed to have to uninstall/delete all of conda to update to a new version of a package?

**Comment by ocefpaf** [comment]
[I agree with all that and understand our frustrations.](https://github.com/conda-forge/gdal-feedstock/issues/219#issuecomment-409234067)

> I'm supposed to have to uninstall/delete all of conda to update to a new version of a package?

Not to mention that the solving steps takes a long time!

**Comment by djhoese** [comment]
Thanks, any idea if this is something that the conda developers are actually considering? I'm worried that an entire training course's laptops will have to have their environments completely removed and reinstalled every time I make an update to my application.

**Comment by ocefpaf** [comment]
> Thanks, any idea if this is something that the conda developers are actually considering?

I know that @kalefranz is always working to make `conda` better.
But this is an issue for the conda GH issue tracker :wink:
